import { z } from 'zod'
import { ConnectorAdapter } from '@jiku/kit'
import type {
  ConnectorAction, ConnectorEvent, ConnectorContext, ConnectorTarget, ConnectorContent,
  ConnectorSendResult, ResolvedEventContext,
  ConnectorSetupSessionState, ConnectorSetupStepResult,
} from '@jiku/types'
import telegramifyMarkdown from 'telegramify-markdown'
import { TelegramClient } from '@mtcute/bun'
import {
  logConnectorEvent,
  createConnectorTarget,
  getConnectorTargetByName,
} from '@jiku-studio/db'
import { getFilesystemService } from '../../../apps/studio/server/src/filesystem/service.ts'
import { UserbotQueue, type UserbotQueuePolicy } from './userbot-queue.ts'
import { REACTIVATE_WAIT_MS, TELEGRAM_MAX_LENGTH } from './shared/constants.ts'
import { lastDeactivateByConnector } from './shared/queues.ts'
import { mapQueueError } from './shared/error-mapper.ts'
import type { PluginConsoleAPI, PluginConsoleLogger } from '@jiku-plugin/studio'

/** Console id for a given Telegram user (self-bot) connector instance. */
export function userConsoleId(connectorId: string): string {
  return `jiku.telegram.user:connector:${connectorId}`
}

// `unknown` typing for the mtcute client because the plugin file would need
// every mtcute type imported just to satisfy TS. Type-aliased to the real
// TelegramClient class statically imported above.
type MtcuteClient = TelegramClient

class TelegramUserAdapter extends ConnectorAdapter {
  readonly id = 'jiku.telegram.user'
  readonly displayName = 'Telegram User (Self-Bot)'
  readonly credentialAdapterId = 'telegram-user'
  override readonly credentialDisplayName = 'Telegram User (Self-Bot)'
  readonly refKeys = ['message_id', 'chat_id', 'thread_id', 'user_id']
  readonly supportedEvents = ['message', 'reaction', 'unreaction', 'edit', 'delete'] as const

  override readonly requiresInteractiveSetup = true

  override readonly credentialSchema = z.object({
    // Required user inputs from my.telegram.org. api_id + api_hash encrypted
    // (auth credential pair). phone_number kept in plain metadata — it's
    // user-facing identifier, useful in UI badges + searchable, and on its
    // own not enough to impersonate.
    api_id: z.string().min(1).describe('secret|API ID from my.telegram.org'),
    api_hash: z.string().min(1).describe('secret|API Hash from my.telegram.org'),
    phone_number: z.string().min(1).describe('Phone number with country code, e.g. +628123456789'),
    // Auto-filled by the setup wizard. session_string IS a full account token
    // (equivalent to bot_token) — stays encrypted. The other three are pure
    // display / metadata, no encryption needed.
    session_string: z.string().optional().describe('secret|Session (auto-generated by Setup wizard, do not edit)'),
    user_id: z.string().optional().describe('Logged-in user ID (auto)'),
    username: z.string().optional().describe('Username (auto)'),
    is_premium: z.string().optional().describe('Premium account (auto)'),
  })

  /**
   * Per-wizard mtcute clients. Keyed by `setup_session_id`. Each entry is the
   * client we stood up for `request_code` and re-use across `verify_code` /
   * `verify_password`. Cleared on completion or wizard cancel.
   *
   * NOT used at runtime — the runtime client lives in `this.client` and is
   * scoped to one credential.
   */
  private setupClients = new Map<string, MtcuteClient>()

  // ─── Multi-tenant per-credential state ────────────────────────────────────
  //
  // Same fix as TelegramBotAdapter: scalar state was a multi-tenant data leak
  // when 2+ userbot credentials activated in one process — second activate
  // overwrote first's `client/queue/myUserId/etc`. Now everything per-credential
  // lives in `userInstances` keyed by connectorId. Scalar fields kept as
  // legacy fallback (ditto `botFor()` pattern).
  //
  // queue is per-instance because Plan §8b's quotas (20/min global, etc.) are
  // PER-SESSION — sharing one queue across credentials would let one session's
  // burst eat into another's quota.

  private userInstances = new Map<string, {
    client: MtcuteClient
    projectId: string
    connectorId: string
    myUserId: string | null
    myUsername: string | null
    myIsPremium: boolean
    queue: UserbotQueue
    activatedAt: number
  }>()

  private clientFor(connectorId: string | null | undefined): MtcuteClient | null {
    if (connectorId) {
      const inst = this.userInstances.get(connectorId)
      if (inst) return inst.client
      return null
    }
    if (this.userInstances.size === 0) return this.client
    if (this.userInstances.size > 1) {
      console.warn(`[telegram.user] clientFor() called WITHOUT connector_id while ${this.userInstances.size} credentials active — defaulting to legacy fallback. Multi-tenant leak risk.`)
    }
    return this.client
  }

  private queueFor(connectorId: string | null | undefined): UserbotQueue {
    if (connectorId) {
      const inst = this.userInstances.get(connectorId)
      if (inst) return inst.queue
    }
    // Legacy fallback — single global queue for code paths not yet updated.
    return this.queue
  }

  private consoleApi: PluginConsoleAPI | null = null
  attachConsole(api: PluginConsoleAPI) { this.consoleApi = api }
  private con(connectorId: string | null | undefined): PluginConsoleLogger | null {
    if (!this.consoleApi || !connectorId) return null
    return this.consoleApi.get(userConsoleId(connectorId), `Telegram User ${connectorId.slice(0, 8)}`)
  }

  // Legacy scalar state (kept as fallback for single-tenant + getter-style reads).
  private client: TelegramClient | null = null
  private projectId: string | null = null
  private connectorId: string | null = null
  private myUserId: string | null = null
  /**
   * Legacy fallback queue. Active credentials get their OWN queue inside
   * `userInstances`. This scalar is only used when a code path doesn't pass
   * connectorId (deprecated — should be eliminated).
   */
  private queue = new UserbotQueue()

  override getSetupSpec() {
    return {
      title: 'Telegram User Account Setup',
      intro: 'You will receive a one-time code on your Telegram app. If you have 2FA enabled, the wizard will ask for your password after the code.',
      steps: [
        {
          id: 'request_code',
          title: 'Send verification code',
          description: 'Telegram will send a one-time code to your phone (via SMS or the Telegram app).',
          inputs: [],
        },
        {
          id: 'verify_code',
          title: 'Enter verification code',
          description: 'Enter the code Telegram just sent to your account.',
          inputs: [
            { name: 'code', type: 'string' as const, required: true, secret: false, label: 'OTP code', placeholder: '12345' },
          ],
        },
        {
          id: 'verify_password',
          title: 'Enter 2FA password',
          description: 'Your account has two-factor authentication enabled.',
          conditional: true,
          inputs: [
            { name: 'password', type: 'string' as const, required: true, secret: true, label: '2FA password' },
          ],
        },
      ],
    }
  }

  override async runSetupStep(stepId: string, input: Record<string, unknown>, state: ConnectorSetupSessionState): Promise<ConnectorSetupStepResult> {
    const fields = state.credential_fields ?? {}
    const apiIdRaw = fields['api_id']
    const apiHash = fields['api_hash']
    const phone = fields['phone_number']
    if (!apiIdRaw || !apiHash || !phone) {
      return { ok: false, error: 'Missing api_id, api_hash, or phone_number on the credential. Save those fields first, then re-run setup.' }
    }
    const apiId = Number(apiIdRaw)
    if (!Number.isFinite(apiId)) {
      return { ok: false, error: 'api_id must be numeric. Get it from my.telegram.org → API Development.' }
    }

    if (stepId === 'request_code') {
      try {
        // const { TelegramClient } = await import('@mtcute/bun') as { TelegramClient: new (opts: { apiId: number; apiHash: string; storage?: string }) => MtcuteClient }
        const client = new TelegramClient({ apiId, apiHash })
        await client.connect()
        const sent = await client.sendCode({ phone })
        // Stash phone_code_hash + client until the user enters the code.
        state.scratch['phone_code_hash'] = sent.phoneCodeHash
        this.setupClients.set(state.session_id, client)
        return { ok: true, next_step: 'verify_code', ui_message: 'Code sent. Check your Telegram app or SMS.' }
      } catch (err) {
        return {
          ok: false,
          error: err instanceof Error ? err.message : String(err),
          hint: 'Verify api_id, api_hash, and phone_number are correct. Phone needs country code (e.g. +628123…).',
        }
      }
    }

    if (stepId === 'verify_code') {
      const client = this.setupClients.get(state.session_id)
      if (!client) {
        return { ok: false, error: 'Setup session expired or `request_code` was never run. Start over from step 1.' }
      }
      const code = String(input['code'] ?? '').trim()
      if (!code) return { ok: false, error: 'OTP code is required.', retry_step: 'verify_code' }
      const phoneCodeHash = String(state.scratch['phone_code_hash'] ?? '')
      try {
        await client.signIn({ phone, phoneCodeHash, phoneCode: code })
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        if (msg.includes('SESSION_PASSWORD_NEEDED')) {
          return { ok: true, next_step: 'verify_password', ui_message: '2FA enabled. Enter your password.' }
        }
        if (msg.includes('PHONE_CODE_INVALID') || msg.includes('PHONE_CODE_EXPIRED')) {
          return { ok: false, error: msg, hint: 'OTP code wrong or expired. Re-check the code and try again.', retry_step: 'verify_code' }
        }
        return { ok: false, error: msg }
      }
      return this.finalizeLogin(client, state)
    }

    if (stepId === 'verify_password') {
      const client = this.setupClients.get(state.session_id)
      if (!client) {
        return { ok: false, error: 'Setup session expired. Start over.' }
      }
      const password = String(input['password'] ?? '')
      if (!password) return { ok: false, error: '2FA password is required.', retry_step: 'verify_password' }
      try {
        await client.checkPassword(password)
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        if (msg.includes('PASSWORD_HASH_INVALID')) {
          return { ok: false, error: msg, hint: 'Wrong 2FA password. Try again.', retry_step: 'verify_password' }
        }
        return { ok: false, error: msg }
      }
      return this.finalizeLogin(client, state)
    }

    return { ok: false, error: `Unknown step: ${stepId}` }
  }

  private async finalizeLogin(client: MtcuteClient, state: ConnectorSetupSessionState): Promise<ConnectorSetupStepResult> {
    try {
      const me = await client.getMe()
      // mtcute exposes session export under different names depending on build
      // (`exportSession` in some versions, `exportStringSession` in others).
      // Try in order; first non-empty result wins. Fail loudly if none yields
      // a string — silent empty session was the bug that made onActivate
      // throw "No session_string" right after a "successful" wizard.
      const c = client as MtcuteClient & {
        exportSession?: () => Promise<string> | string
        exportStringSession?: () => Promise<string> | string
      }
      let session: string | undefined
      if (typeof c.exportSession === 'function') {
        session = await c.exportSession()
      }
      if (!session && typeof c.exportStringSession === 'function') {
        session = await c.exportStringSession()
      }
      console.log(`[telegram.user] finalizeLogin: me=@${me.username ?? me.id} (id=${me.id}, premium=${!!me.isPremium}); session_len=${session?.length ?? 0}`)
      if (!session || typeof session !== 'string' || session.length === 0) {
        return {
          ok: false,
          error: 'mtcute did not return a session string. Tried `exportSession()` and `exportStringSession()` — both returned empty/null. Check @mtcute/bun version installed; this build may use a different export method.',
          hint: 'Run `bun pm ls @mtcute/bun` to confirm version. The adapter expects v0.27+ semantics.',
        }
      }
      try { await client.disconnect() } catch { /* best-effort */ }
      this.setupClients.delete(state.session_id)
      return {
        ok: true,
        complete: true,
        fields: {
          session_string: session,
          user_id: String(me.id),
          username: me.username ?? '',
          is_premium: me.isPremium ? 'true' : 'false',
        },
        ui_message: `Logged in as @${me.username ?? me.id} (${me.isPremium ? 'Premium' : 'Free'}). Setup complete — credential is now ready to activate.`,
      }
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }
  }

  // ─── Runtime ──────────────────────────────────────────────────────────────

  override async onActivate(ctx: ConnectorContext): Promise<void> {
    this.con(ctx.connectorId)?.info('Userbot activating', { project_id: ctx.projectId })
    const session = ctx.fields['session_string']
    const apiIdRaw = ctx.fields['api_id']
    const apiHash = ctx.fields['api_hash']
    if (!session) {
      throw new Error('No session_string on the credential. Run the interactive Setup wizard first.')
    }
    if (!apiIdRaw || !apiHash) throw new Error('Missing api_id / api_hash on the credential.')
    const apiId = Number(apiIdRaw)
    if (!Number.isFinite(apiId)) throw new Error('api_id must be numeric.')

    // Pre-connect wait — mirror bot adapter behaviour for the same reasons:
    //
    //   (a) Reactivate within same process (Stop+Start / settings save) → wait
    //       remainder of the 30s window since last deactivate. mtcute can hit
    //       AUTH_KEY_DUPLICATED if the previous client closed too recently and
    //       Telegram still considers the session live.
    //
    //   (b) Fresh boot (no entry in map) → wait `TELEGRAM_BOOT_POLL_DELAY_MS`
    //       (default 10s) so a previous container in a zero-downtime deploy has
    //       time to release its mtcute session before this one connects on the
    //       same `session_string`. Without this, both processes connect with
    //       the same auth_key and Telegram revokes one with AUTH_KEY_DUPLICATED.
    {
      const lastDeact = lastDeactivateByConnector.get(ctx.connectorId)
      if (lastDeact) {
        const elapsed = Date.now() - lastDeact
        const remain = REACTIVATE_WAIT_MS - elapsed
        if (remain > 0) {
          console.log(`[telegram.user] waiting ${Math.ceil(remain / 1000)}s for Telegram session-slot release before connecting`)
          await new Promise<void>(r => setTimeout(r, remain))
        }
      } else {
        const bootDelayMs = Number(process.env['TELEGRAM_BOOT_POLL_DELAY_MS'] ?? 10_000)
        if (bootDelayMs > 0) {
          console.log(`[telegram.user] fresh-boot wait ${Math.ceil(bootDelayMs / 1000)}s before connecting (lets old zero-downtime container release session)`)
          await new Promise<void>(r => setTimeout(r, bootDelayMs))
        }
      }
    }

    // mtcute v0.27 API: TelegramClient constructor only accepts core options
    // (apiId, apiHash, storage). Session is loaded via `client.start({ session })`
    // which ALSO starts the updates loop — without `start()`, no inbound updates
    // are dispatched to onNewMessage Emitter. Previously we used `connect()`
    // which only opens the network but doesn't enable updates dispatching.
    // Cast through unknown — actual mtcute TelegramClient has hundreds of
    // methods we don't bother typing. Runtime usage is duck-typed via the
    // narrow `MtcuteClient` interface + extra cast at use site.
    // const mod = await import('@mtcute/bun') as unknown as {
    //   TelegramClient: new (opts: { apiId: number; apiHash: string; storage?: string }) => MtcuteClient
    // }
    // const { TelegramClient } = mod
    // Per-credential SQLite storage path so multi-tenant userbots don't share
    // a single client.session file (would race + corrupt). Use connectorId.
    const storagePath = `userbot-${ctx.connectorId}.session`
    this.client = new TelegramClient({ apiId, apiHash, storage: storagePath })
    this.projectId = ctx.projectId
    this.connectorId = ctx.connectorId

    // Multi-tenant: each credential gets its OWN UserbotQueue (Plan §8b
    // quotas are per-Telegram-session, not shared). Build it now so we can
    // hand to the instance entry below.
    const instanceQueue = new UserbotQueue()
    const policyRaw = ctx.fields['queue_policy']
    if (policyRaw) {
      try {
        const parsed = JSON.parse(policyRaw) as Partial<UserbotQueuePolicy>
        instanceQueue.setPolicy(parsed)
      } catch { /* ignore — keep defaults */ }
    }
    instanceQueue.onEvent((event) => {
      console.log(`[telegram.user] queue event (connector=${ctx.connectorId}):`, event)
    })
    // Keep legacy scalar in sync so any code path that reads `this.queue`
    // gets the most-recent instance's queue (single-tenant fallback).
    this.queue = instanceQueue

    // Stash this credential's runtime state under its connectorId.
    this.userInstances.set(ctx.connectorId, {
      client: this.client,
      projectId: ctx.projectId,
      connectorId: ctx.connectorId,
      myUserId: null,
      myUsername: null,
      myIsPremium: false,
      queue: instanceQueue,
      activatedAt: Date.now(),
    })

    try {
      const c0 = this.client as TelegramClient
      // start() handles session import + auth check + updates loop in one go.
      // Falls back to connect()+importSession() for older mtcute builds.
      if (typeof c0.start === 'function') {
        await c0.start({ session })
        c0.onNewMessage.add((msg) => {
          console.log(msg.text)
        })
      } else if (typeof c0.importSession === 'function') {
        await c0.importSession(session)
        await this.client.connect()
      } else {
        await this.client.connect()
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      if (msg.includes('AUTH_KEY_UNREGISTERED') || msg.includes('AUTH_KEY_DUPLICATED')) {
        this.queue.markSessionExpired()
        // Surface a clear "session expired" so the credential UI prompts re-setup.
        throw new Error(`SESSION_EXPIRED: ${msg} — re-run the Setup wizard.`)
      }
      throw err
    }

    try {
      const me = await this.client.getMe()
      this.myUserId = String(me.id)
      this.myUsername = me.username ?? null
      this.myIsPremium = me.isPremium === true
      // Mirror identity into per-instance map.
      const inst = this.userInstances.get(ctx.connectorId)
      if (inst) {
        inst.myUserId = this.myUserId
        inst.myUsername = this.myUsername
        inst.myIsPremium = this.myIsPremium
      }
      this.con(ctx.connectorId)?.info(`Identity cached: @${this.myUsername ?? '(no username)'}`, { user_id: this.myUserId, premium: this.myIsPremium })
    } catch { /* non-fatal */ }

    // Inbound — wire 'new_message' to ConnectorEvent shape. mtcute's pub-sub
    // API name differs across versions / build flavours:
    //   - v0.x worker:        client.on('new_message', handler)
    //   - v0.27+ method:      client.onNewMessage.add(handler) / client.onNewMessage(handler)
    //   - dispatcher pattern: client.dispatcher.onNewMessage(handler)
    //   - updates namespace:  client.updates.on('new_message', handler)
    // Try each in order; first one that's a function wins. Failing all:
    // log + continue (outbound still works, just no inbound routing).
    const handler = async (raw: unknown) => {
      try {
        // Diagnostic: every raw mtcute message arrival, BEFORE normalize.
        // Lets operator confirm whether the wired pub-sub method is firing
        // at all (separate from "normalize returned null"). Sample chat info
        // so we don't dump massive object — just enough to identify it.
        const r = raw as { id?: number | bigint; chat?: { id?: number | bigint; chatType?: string; title?: string }; sender?: { id?: number | bigint; username?: string }; text?: string }
        const senderTag = r?.sender?.username ? `@${r.sender.username}` : String(r?.sender?.id ?? '?')
        const inboundSummary = `msg=${String(r?.id ?? '?')} chat=${String(r?.chat?.id ?? '?')} ${r?.chat?.chatType ?? 'dm'}`
        const textPreview = (r?.text ?? '').slice(0, 60)
        this.con(ctx.connectorId)?.info(`[${senderTag}] ${inboundSummary}: ${textPreview}`, {
          msg_id: String(r?.id ?? ''),
          chat_id: String(r?.chat?.id ?? ''),
          sender: senderTag,
        })
        // Pass ctx.connectorId so multi-tenant userbots produce events with the
        // RIGHT connector_id (legacy `this.connectorId` would point to the
        // most-recently-activated credential — wrong for credential A's inbound).
        const event = this.normalizeInbound(raw, ctx.connectorId)
        if (!event) {
          this.con(ctx.connectorId)?.warn(`[${senderTag}] DROPPED msg=${String(r?.id ?? '?')} — missing required field`)
          return
        }

        // Auto-register forum topic target on first sighting (fire-and-forget).
        // Idempotent via getConnectorTargetByName — safe to call on every
        // topic message. Mirrors bot-adapter.ts:841. Needs connectorId + the
        // event to have thread_id (only populated when isTopicMessage=true).
        const tid = event.ref_keys['thread_id']
        if (tid && ctx.connectorId) {
          const chatTitleRaw = (r?.chat as { title?: string } | undefined)?.title
          void this.autoRegisterForumTopic(
            String(r?.chat?.id ?? ''),
            chatTitleRaw,
            tid,
            ctx.connectorId,
          )
        }
        // Mirror bot adapter's pattern: arrival row first (status=received),
        // OUTSIDE the routing pipeline, so connector_events table reflects
        // truth even if the router stalls. Without this, no row at all
        // appears in the Channels Events tab from inbound.
        // Thread the arrival row id into event.metadata.arrival_event_id so the
        // downstream event-router can UPDATE the same row instead of INSERTing
        // a duplicate as it transitions through the routing pipeline.
        if (this.connectorId) {
          try {
            const row = await logConnectorEvent({
              connector_id: this.connectorId!,
              event_type: event.type,
              direction: 'inbound',
              ref_keys: event.ref_keys,
              payload: event as unknown as Record<string, unknown>,
              raw_payload: raw,
              status: 'received',
            })
            event.metadata = { ...(event.metadata ?? {}), arrival_event_id: row.id }
          } catch (err) {
            this.con(ctx.connectorId)?.error(`[${senderTag}] logArrival failed: ${err instanceof Error ? err.message : String(err)}`)
          }
        }
        ctx.onEvent(event).catch(err => this.con(ctx.connectorId)?.error(`[${senderTag}] onEvent error: ${err instanceof Error ? err.message : String(err)}`))
      } catch (err) {
        this.con(ctx.connectorId)?.error(`inbound normalize error: ${err instanceof Error ? err.message : String(err)}`)
      }
    }
    // mtcute v0.27 API: emitters under `client.onNewMessage` / `client.onUpdate`
    // / `client.onRawUpdate`. Each is an `Emitter<T>` from @fuman/utils with
    // an `add(handler)` method. Old `client.on('new_message', ...)` does NOT
    // exist on this build — confirmed by inspecting node_modules/@mtcute.
    type EmitterLike = { add: (h: (v: unknown) => void) => void }
    const c = this.client as unknown as {
      onNewMessage?: EmitterLike
      onRawUpdate?: EmitterLike
      onUpdate?: EmitterLike
    }
    let wired = false
    const nm = c.onNewMessage
    if (nm && typeof nm.add === 'function') {
      try { nm.add(handler); wired = true } catch { /* try next */ }
    }
    // Fallback to onUpdate (parsed updates — needs filtering for 'new_message').
    const ou = c.onUpdate
    if (!wired && ou && typeof ou.add === 'function') {
      try {
        ou.add((u: unknown) => {
          const upd = u as { name?: string; data?: unknown }
          if (upd?.name === 'new_message' && upd.data) handler(upd.data)
        })
        wired = true
      } catch { /* try next */ }
    }
    if (!wired) {
      console.warn(`[telegram.user] could not wire inbound handler — no recognised mtcute pub-sub method found. Outbound + actions still work; inbound message routing is DISABLED until adapter is updated for this @mtcute/bun build.`)
    } else {
      console.log(`[telegram.user] inbound handler wired for connector=${ctx.connectorId}`)
    }

    console.log(`[telegram.user] activated — logged in as user_id=${this.myUserId}`)
    this.con(ctx.connectorId)?.info(`Userbot activated — user_id=${this.myUserId}`, { wired_inbound: wired })
  }

  override async onDeactivate(connectorId?: string): Promise<void> {
    // Multi-tenant: tear down ONLY the matching credential's instance. If
    // connectorId omitted (legacy callers), fall back to "the only one" or
    // refuse if multiple are active.
    let targetId: string | null = connectorId ?? null
    if (!targetId) {
      if (this.userInstances.size === 1) targetId = [...this.userInstances.keys()][0]!
      else if (this.userInstances.size > 1) {
        console.warn(`[telegram.user] onDeactivate() called WITHOUT connectorId while ${this.userInstances.size} credentials active — refusing (would tear down wrong one).`)
        return
      } else {
        return
      }
    }
    const inst = this.userInstances.get(targetId)
    if (!inst) return

    this.con(targetId)?.info('Userbot deactivating')
    lastDeactivateByConnector.set(targetId, Date.now())
    try { await inst.client.disconnect() } catch { /* best-effort */ }
    try { if (inst.client.close) await inst.client.close() } catch { /* best-effort */ }
    this.userInstances.delete(targetId)

    // If we just tore down the credential whose state lived in the legacy
    // scalars, repoint scalars to the next-newest remaining instance (or
    // null if none remain).
    if (this.connectorId === targetId) {
      this.client = null
      this.projectId = null
      this.connectorId = null
      this.myUserId = null
      this.myUsername = null
      this.myIsPremium = false
      const remaining = [...this.userInstances.values()].sort((a, b) => b.activatedAt - a.activatedAt)[0]
      if (remaining) {
        this.client = remaining.client as TelegramClient
        this.projectId = remaining.projectId
        this.connectorId = remaining.connectorId
        this.myUserId = remaining.myUserId
        this.myUsername = remaining.myUsername
        this.myIsPremium = remaining.myIsPremium
        this.queue = remaining.queue
      }
    }
    console.log(`[telegram.user] disconnected for connector=${targetId} (${this.userInstances.size} remain)`)
  }

  private myUsername: string | null = null
  private myIsPremium: boolean = false

  override getIdentity(connectorId?: string) {
    // Multi-tenant: return THIS connector's identity, not the legacy scalar.
    const inst = connectorId ? this.userInstances.get(connectorId) : null
    const username = inst?.myUsername ?? this.myUsername
    const userId = inst?.myUserId ?? this.myUserId
    const isPremium = inst?.myIsPremium ?? this.myIsPremium
    if (!userId && !username) return null
    return {
      name: username ?? `user:${userId}`,
      username: username ? `@${username}` : null,
      user_id: userId,
      metadata: {
        kind: 'userbot',
        is_premium: isPremium,
        connector_id: inst?.connectorId ?? this.connectorId ?? null,
      },
    }
  }

  override parseEvent(): ConnectorEvent | null {
    // Inbound events come through `client.on('new_message')` in onActivate
    // (push model, not pull). External webhook adapters use parseEvent; userbot
    // doesn't have one.
    return null
  }

  /**
   * Map an mtcute incoming message into the canonical ConnectorEvent shape.
   * This is best-effort — mtcute's wrapped Message has many fields; we pull
   * the ones the Jiku event-router cares about.
   */
  private normalizeInbound(raw: unknown, connectorIdHint?: string): ConnectorEvent | null {
    const m = raw as Record<string, unknown> & {
      id?: number
      chat?: { id?: number | bigint; chatType?: string; title?: string; username?: string; firstName?: string; isForum?: boolean }
      sender?: { id?: number | bigint; isBot?: boolean; username?: string; firstName?: string }
      text?: string
      date?: Date | number
      isTopicMessage?: boolean
      isMention?: boolean
      entities?: Array<{ type?: string; offset?: number; length?: number; userId?: number | bigint; user?: { id?: number | bigint } }> | null
      replyToMessage?: {
        threadId?: number | null
        isForumTopic?: boolean
        sender?: { id?: number | bigint } | null
        senderId?: number | bigint | null
      } | null
    }
    if (!m || typeof m !== 'object' || !m.id || !m.chat) return null
    const chatId = String(m.chat.id ?? '')
    if (!chatId) return null
    // Skip our own outbound — userbot also receives its own sent messages.
    // Resolve identity per-instance: if we know which connector this event
    // came in on (from the activate-time closure), use that instance's
    // myUserId — falls back to scalar for legacy callers.
    const inst = connectorIdHint ? this.userInstances.get(connectorIdHint) : null
    const myUserId = inst?.myUserId ?? this.myUserId
    if (m.sender && myUserId && String(m.sender.id ?? '') === myUserId) return null

    // mtcute discriminator: `Message.chat` returns `Peer = User | Chat`. Only
    // Chat instances have `.chatType` getter ('group' | 'supergroup' | 'channel'
    // | 'gigagroup' | 'monoforum'). Absence of `chatType` means the chat is a
    // User → DM. This was the bug behind "no pairing request appears" — old
    // code checked `chatType === 'group'` and got undefined for DMs (correct
    // behavior — DMs ARE chatType-less), but DM path's pending-identity flow
    // also runs only when scope_key is undefined (which it is for DMs anyway).
    // The actual fix here is making `chat_type` metadata accurate for both
    // branches so downstream / UI sees 'private' for DMs instead of 'n/a'.
    const ct = m.chat.chatType
    const isGroup = ct === 'group' || ct === 'supergroup' || ct === 'channel' || ct === 'gigagroup'
    const chatType: string = ct ?? 'private'  // No chatType ⇒ Peer is User ⇒ DM

    // Forum topics: mtcute flags `isTopicMessage: true` on messages inside a
    // topic and exposes the topic's root message id via `replyToMessage.threadId`.
    // Grammy's `message_thread_id` is the equivalent. Without this the router
    // can't match topic-scoped bindings (ref_keys mismatch → event dropped),
    // and auto-pairing creates chat-level drafts that ignore which topic the
    // message came from. Mirrors bot-adapter.ts:1001 + scope_key convention.
    const threadId = m.isTopicMessage && m.replyToMessage?.threadId != null
      ? String(m.replyToMessage.threadId)
      : undefined
    const scopeKey = isGroup
      ? (threadId ? `group:${chatId}:topic:${threadId}` : `group:${chatId}`)
      : undefined

    // Mention + reply-to-self detection — parity with bot-adapter.ts:918-944
    // so binding `trigger_mode='mention'` works the same way on userbot as on
    // bot. Layered strategy:
    //   1. `m.isMention` — mtcute's precomputed "self is mentioned" flag,
    //      populated server-side or from the entity table. Authoritative.
    //   2. Entity scan fallback — covers cases where `isMention` is absent or
    //      stale by cross-checking `@myUsername` + user-id text mentions.
    //      Also handles forwards / edited messages where the precomputed flag
    //      can drift.
    //   3. `replyToMessage.sender.id === myUserId` → `bot_replied_to`. Note:
    //      Telegram also attaches a synthetic `replyToMessage` for forum
    //      topic membership (threadId = topic root, sender = topic creator).
    //      That's captured here too if the topic-root sender happens to be
    //      the userbot — which is semantically fine: we own the topic root.
    let botMentioned = m.isMention === true
    if (!botMentioned && Array.isArray(m.entities) && typeof m.text === 'string') {
      const text = m.text
      const username = (inst?.myUsername ?? this.myUsername)?.toLowerCase()
      const uid = inst?.myUserId ?? this.myUserId
      for (const ent of m.entities) {
        if (!ent || typeof ent.type !== 'string') continue
        if (ent.type === 'mention' && username && typeof ent.offset === 'number' && typeof ent.length === 'number') {
          const slice = text.slice(ent.offset, ent.offset + ent.length).toLowerCase()
          if (slice === `@${username}`) { botMentioned = true; break }
        }
        // mtcute exposes user-id text-mention as `type: 'text_mention'` on
        // the wrapped entity (same name grammy uses at the Bot API layer);
        // older builds surface it as `mentionName`. Accept both.
        if ((ent.type === 'text_mention' || ent.type === 'mentionName') && uid) {
          const entUid = ent.user?.id ?? ent.userId
          if (entUid != null && String(entUid) === uid) { botMentioned = true; break }
        }
      }
    }
    const replySenderId = m.replyToMessage?.sender?.id ?? m.replyToMessage?.senderId
    const myUid = inst?.myUserId ?? this.myUserId
    const botRepliedTo = replySenderId != null && myUid != null && String(replySenderId) === myUid

    return {
      type: 'message',
      // IMPORTANT: this is the ADAPTER id ('jiku.telegram.user'), NOT the
      // connector UUID. event-router uses it to find which connector row
      // owns this event via `connector.plugin_id === event.connector_id`.
      // Putting a UUID here makes EVERY event silently drop because no
      // plugin_id will match (bot adapter pattern is the same — `this.id`).
      connector_id: this.id,
      ref_keys: {
        message_id: String(m.id),
        chat_id: chatId,
        ...(threadId ? { thread_id: threadId } : {}),
      },
      scope_key: scopeKey,
      sender: {
        external_id: String(m.sender?.id ?? ''),
        display_name: m.sender?.firstName ?? m.sender?.username ?? undefined,
        username: m.sender?.username ?? undefined,
        is_bot: m.sender?.isBot === true,
      },
      content: { text: m.text ?? '', raw: m },
      metadata: {
        chat_title: m.chat.title ?? m.chat.firstName,
        chat_type: chatType,
        ...(botMentioned ? { bot_mentioned: true } : {}),
        ...(botRepliedTo ? { bot_replied_to: true } : {}),
        // Plan 25 add-on — reply context. mtcute exposes RepliedMessageInfo
        // via `m.replyToMessage` (getter). Snapshot the useful fields so the
        // event-router can inject a Reply chain into connector_context. The
        // raw object's getters don't survive JSON serialization, so we copy
        // explicit primitives here.
        ...(extractMtcuteReply(m as unknown as { replyToMessage?: unknown })),
      },
      raw_payload: m,
      timestamp: m.date instanceof Date ? m.date : new Date((Number(m.date ?? 0)) * 1000),
    }
  }

  override async sendMessage(target: ConnectorTarget, content: ConnectorContent): Promise<ConnectorSendResult> {
    // Multi-tenant: pick THIS target's client + queue (per-credential isolation).
    const client = this.clientFor(target.connector_id)
    const queue = this.queueFor(target.connector_id)
    if (!client) return { success: false, error: target.connector_id
      ? `No active userbot instance for connector_id=${target.connector_id}`
      : 'Userbot client not connected' }

    // Resolve chat + thread (topic) — explicit ref_keys > scope_key fallback.
    // Same precedence as TelegramBotAdapter.sendMessage (bot-adapter.ts:1565-1575).
    let chatId = target.ref_keys['chat_id']
    let threadId = target.ref_keys['thread_id']
    const scope = content.target_scope_key ?? target.scope_key
    if (scope) {
      const resolved = this.targetFromScopeKey(scope)
      if (resolved) {
        chatId = chatId ?? resolved.ref_keys['chat_id']
        threadId = threadId ?? resolved.ref_keys['thread_id']
      }
    }
    if (!chatId) return { success: false, error: 'Missing chat_id' }
    const text = content.text ?? ''
    if (!text) return { success: false, error: 'Empty text' }

    // mtcute v0.27 high-level API does NOT have parseMode in send opts —
    // `text: InputText` is `string | TextWithEntities`. Plain string = sent
    // raw (no parsing). Markdown rendering requires `TextWithEntities` from
    // mtcute's `md`-template helper (separate package). For now: send PLAIN.
    // Running `telegramifyMarkdown(...escape)` here was producing visible
    // backslashes (`\-`, `\\`) at the user's screen because Telegram never
    // parsed them — the parseMode flag was silently ignored.
    //
    // Future: import @mtcute/markdown-parser to support markdown formatting.
    const finalText = text
    const opts: Record<string, unknown> = {}
    if (content.params) {
      for (const [k, v] of Object.entries(content.params)) {
        if (v === undefined || v === null) continue
        opts[k] = v
      }
    }

    // Build mtcute `replyTo` — single NUMBER (mtcute v0.27 `sendText` opts
    // accept only `replyTo: number | Message`, plain `{messageId, threadId}`
    // crashes at send-common.js:27). Order of preference:
    //  1. Caller-provided `content.params.replyTo` (already in opts) wins if
    //     it's already a number or Message instance — agent's explicit choice.
    //  2. Literal reply to the user's inbound message via
    //     `target.reply_to_ref_keys.message_id`. Telegram server auto-inherits
    //     the topic from the replied message AND shows the chat-bubble quote.
    //  3. Topic-route fallback via `threadId` — no message to reply to, just
    //     drop the message into the right topic (replyTo=threadId is mtcute's
    //     idiom for this; see answerText in send-answer.js:9).
    const replyToMsgId = target.reply_to_ref_keys?.['message_id']
    const existingReplyTo = opts['replyTo']
    const callerAlreadySet = typeof existingReplyTo === 'number'
      || (existingReplyTo && typeof existingReplyTo === 'object' && 'id' in (existingReplyTo as Record<string, unknown>))
    if (!callerAlreadySet) {
      if (replyToMsgId) {
        opts['replyTo'] = Number(replyToMsgId)
      } else if (threadId !== undefined) {
        opts['replyTo'] = Number(threadId)
      } else {
        // If existing is a bogus object (e.g. caller passed `{messageId}` form
        // which would crash mtcute), strip it rather than propagate the crash.
        if (existingReplyTo && typeof existingReplyTo === 'object') {
          const obj = existingReplyTo as Record<string, unknown>
          if (typeof obj['messageId'] === 'number') opts['replyTo'] = obj['messageId']
          else delete opts['replyTo']
        }
      }
    }

    const peer = chatId.startsWith('-') || /^\d+$/.test(chatId) ? Number(chatId) : chatId

    // simulate_typing for userbot: real-account typing indicator + dwell time
    // proportional to text length (mimics human typing speed). Bot adapter
    // does fake-typing via edits; userbot can use the genuine TG typing
    // status which feels much more natural to the recipient.
    if (content.simulate_typing) {
      try {
        const c = client as MtcuteClient & { sendTyping?: (peer: string | number | bigint, status?: string) => Promise<unknown> }
        if (c.sendTyping) {
          await c.sendTyping(peer, 'typing').catch(() => {})
          // Dwell ≈ 30 chars/sec, capped 300ms-3000ms. Quick reply feels snappy,
          // long replies show meaningful "typing..." duration.
          const dwellMs = Math.min(3000, Math.max(300, Math.floor(finalText.length * 33)))
          await new Promise<void>(r => setTimeout(r, dwellMs))
        }
      } catch { /* best-effort */ }
    }

    try {
      this.con(target.connector_id)?.info(`outbound → chat_id=${chatId} len=${finalText.length}`, { chat_id: chatId })
      const queued = await queue.enqueue<{ id?: number; chat?: { id?: number | bigint } } | undefined>(
        { chatId },
        () => client.sendText(peer, finalText, opts) as Promise<{ id?: number; chat?: { id?: number | bigint } } | undefined>,
        'send_message',
      )
      const res = queued.result
      this.con(target.connector_id)?.info(`outbound OK message_id=${res?.id ?? 'n/a'}`, { chat_id: chatId })
      return {
        success: true,
        ref_keys: {
          message_id: String(res?.id ?? ''),
          chat_id: String(res?.chat?.id ?? chatId),
        },
        raw_payload: { ...res, queue: { delay_ms_applied: queued.delay_ms_applied } },
      }
    } catch (err) {
      return mapQueueError(err)
    }
  }

  /**
   * Streaming outbound via the event-router handoff hook (ADR-087).
   *
   * Mirrors `TelegramBotAdapter.handleResolvedEvent` but tuned for userbot
   * MTProto constraints:
   *  - **Plain text only.** mtcute's high-level `sendText` / `editMessage`
   *    accepts a plain string (no parseMode in this build's shape). The bot
   *    adapter's MarkdownV2 finalize step is skipped here; tool chips render
   *    as literal `[🔧] name` / `[☑️] name` without italic wrapping.
   *  - **Slower debounce.** First edit fires 1500ms after the first chunk
   *    (so the user sees motion quickly); subsequent edits are debounced
   *    5000ms. Userbot accounts get FLOOD_WAIT / PEER_FLOOD much more
   *    aggressively than bots — this pacing keeps well under any realistic
   *    threshold (~12 edits/min) while still showing progress.
   *  - **Queue-respecting.** Every placeholder / edit / continuation call
   *    goes through `UserbotQueue.enqueue(...)` so the global 20/min sliding
   *    quota + per-chat 1000ms min gap + `FLOOD_WAIT` pause latch all still
   *    apply. Edit failures (queue-mapped errors or mtcute "not modified")
   *    are swallowed for intermediate ticks; the final edit falls back to
   *    a plain sendText if even that fails.
   *  - **editMessage probe.** Some `@mtcute/bun` builds don't expose
   *    `editMessage`. When missing, we degrade to a single final `sendText`
   *    at stream end (no placeholder, no intermediate edits).
   */
  override async handleResolvedEvent(ctx: ResolvedEventContext): Promise<void> {
    const client = this.clientFor(ctx.connectorId)
    const queue = this.queueFor(ctx.connectorId)
    if (!client) {
      this.con(ctx.connectorId)?.error('handleResolvedEvent: no active client for this connector')
      return
    }

    const chatId = ctx.event.ref_keys['chat_id']
    if (!chatId) return
    const peer: string | number = chatId.startsWith('-') || /^\d+$/.test(chatId) ? Number(chatId) : chatId

    // Reply + topic routing — mtcute v0.27 `sendText` opts quirk:
    //   - `replyTo` accepts a NUMBER (message id) OR a wrapped Message
    //     instance. Plain objects like `{ messageId, threadId }` crash with
    //     `params.replyTo?.chat.inputPeer` (send-common.js:27) because mtcute
    //     tries to read `.chat.inputPeer` off the object to fill replyToPeer.
    //   - The TL `top_msg_id` field (for forum topics) is NOT exposed at the
    //     high-level send API in this version. mtcute's own `answerText`
    //     (send-answer.js:9) hacks around this by using `replyTo = threadId`
    //     for topic messages — i.e. "reply to the topic's root message" to
    //     route the send into the topic.
    //
    // Strategy:
    //   1. If we have the user's message id → `replyTo: <messageId>`.
    //      Telegram server auto-inherits the topic from the replied message,
    //      AND the chat bubble shows a "replying to …" quote. Best of both.
    //   2. Else if only threadId is available → `replyTo: <threadId>` — just
    //      route into the topic (no visual reply). Fallback for cases where
    //      we somehow lose the source message_id.
    //   3. Else → no opts, send naked.
    const replyToMsgId = ctx.event.ref_keys['message_id']
    const threadId = ctx.event.ref_keys['thread_id']
    const sendOpts: Record<string, unknown> = {}
    if (replyToMsgId) {
      sendOpts['replyTo'] = Number(replyToMsgId)
    } else if (threadId) {
      sendOpts['replyTo'] = Number(threadId)
    }

    const cExt = client as MtcuteClient & {
      editMessage?: (opts: { chatId: string | number | bigint; message: number; text: string }) => Promise<unknown>
    }
    const hasEdit = typeof cExt.editMessage === 'function'

    // 1. Placeholder (only when edits are available — otherwise we'd strand a
    //    ⌛ message on the user's screen if editMessage is missing).
    let currentMsgId: number | null = null
    if (hasEdit) {
      try {
        const queued = await queue.enqueue<{ id?: number } | undefined>(
          { chatId },
          () => client.sendText(peer, '⌛', sendOpts) as Promise<{ id?: number } | undefined>,
          'send_message',
        )
        const mid = queued.result?.id
        if (typeof mid === 'number') currentMsgId = mid
      } catch (err) {
        // Queue rejected (FLOOD_WAIT / PEER_FLOOD / SESSION_EXPIRED). Bail —
        // no placeholder, no streaming. The final send at the end will
        // likely hit the same latch, but we'll try so the user at least
        // gets an error surfaced via event-router logging.
        this.con(ctx.connectorId)?.warn(`placeholder rejected: ${err instanceof Error ? err.message : String(err)}`)
      }
    }

    // 2. Start run + tee stream.
    const run = await ctx.startRun()
    const [selfStream, observerStream] = run.stream.tee()
    const observer = ctx.registerObserverStream(observerStream)

    // 3. Streaming render state — same interleaved model as bot adapter.
    type ToolItem = { id: string; name: string; status: 'running' | 'done' | 'error' }
    type Segment = { type: 'text'; content: string } | { type: 'tools'; items: ToolItem[] }
    const segments: Segment[] = []
    const toolIndex = new Map<string, { groupIdx: number; itemIdx: number }>()

    const appendText = (delta: string): void => {
      if (!delta) return
      const last = segments[segments.length - 1]
      if (last && last.type === 'text') last.content += delta
      else segments.push({ type: 'text', content: delta })
    }

    const pushTool = (id: string, name: string): void => {
      if (toolIndex.has(id)) return
      const last = segments[segments.length - 1]
      if (last && last.type === 'tools') {
        last.items.push({ id, name, status: 'running' })
        toolIndex.set(id, { groupIdx: segments.length - 1, itemIdx: last.items.length - 1 })
      } else {
        segments.push({ type: 'tools', items: [{ id, name, status: 'running' }] })
        toolIndex.set(id, { groupIdx: segments.length - 1, itemIdx: 0 })
      }
    }

    const updateToolStatus = (id: string | undefined, status: 'done' | 'error'): void => {
      const pos = id ? toolIndex.get(id) : undefined
      if (pos) {
        const group = segments[pos.groupIdx]
        if (group?.type === 'tools') {
          const item = group.items[pos.itemIdx]
          if (item) item.status = status
        }
        return
      }
      for (let i = segments.length - 1; i >= 0; i--) {
        const s = segments[i]
        if (s?.type !== 'tools') continue
        for (let j = s.items.length - 1; j >= 0; j--) {
          if (s.items[j]!.status === 'running') { s.items[j]!.status = status; return }
        }
      }
    }

    const iconFor = (s: 'running' | 'done' | 'error'): string =>
      s === 'done' ? '[☑️]' : s === 'error' ? '[❌]' : '[🔧]'

    const allTools = (): ToolItem[] => {
      const out: ToolItem[] = []
      for (const seg of segments) if (seg.type === 'tools') out.push(...seg.items)
      return out
    }

    let usageInput = 0
    let usageOutput = 0
    let providerId: string | null = null
    let modelId: string | null = null
    type RunSnapshot = { system_prompt?: string; messages?: unknown[]; response?: string; tools?: string[]; adapter?: string }
    let runSnapshot: RunSnapshot | null = null

    // First edit after 1500ms gives the user fast feedback that something's
    // happening; subsequent edits pace at 5000ms to stay well under userbot
    // flood thresholds while still feeling live.
    const FIRST_EDIT_MS = 1500
    const SUBSEQUENT_EDIT_MS = 5000
    let editCount = 0
    let editChain: Promise<void> = Promise.resolve()
    let pendingTimer: NodeJS.Timeout | null = null
    let finalizing = false

    // Plain-text render. `---` separators render literally on Telegram —
    // no MarkdownV2 involvement so no escaping needed.
    const renderPlain = (): string => {
      if (segments.length === 0) return '⌛'
      const parts = segments.map(seg => {
        if (seg.type === 'text') return seg.content
        return seg.items.map(t => `${iconFor(t.status)} ${t.name}`).join('\n')
      })
      return parts.join('\n---\n')
    }

    const overflow = (): boolean => renderPlain().length > TELEGRAM_MAX_LENGTH - 200

    // mtcute surfaces Telegram's "MESSAGE_NOT_MODIFIED" when edit content
    // matches the current message content byte-for-byte — that's a no-op
    // success, not a failure. Swallow silently.
    const isNotModifiedError = (err: unknown): boolean => {
      const msg = err instanceof Error ? err.message : String(err)
      return /MESSAGE_NOT_MODIFIED|message.*not modified/i.test(msg)
    }

    const runEdit = async (text: string): Promise<boolean> => {
      if (!hasEdit || currentMsgId == null) return false
      try {
        await queue.enqueue<unknown>(
          { chatId },
          () => cExt.editMessage!({ chatId: peer, message: currentMsgId!, text }),
          'edit_message',
        )
        return true
      } catch (err) {
        if (isNotModifiedError(err)) return true
        // FLOOD_WAIT / transient — skip this tick. The next debounced edit
        // (or the finalize) will retry with more content.
        return false
      }
    }

    const flushEdit = () => {
      pendingTimer = null
      if (finalizing) return
      editChain = editChain.then(async () => {
        if (finalizing) return
        if (overflow() && hasEdit) {
          // Land what we have, start a fresh placeholder for continuation.
          await runEdit(renderPlain())
          try {
            const queued = await queue.enqueue<{ id?: number } | undefined>(
              { chatId },
              () => client.sendText(peer, '⌛', sendOpts) as Promise<{ id?: number } | undefined>,
              'send_message',
            )
            const mid = queued.result?.id
            if (typeof mid === 'number') currentMsgId = mid
          } catch {
            // Continuation send rejected by queue — stop mid-stream; we'll
            // still accumulate segments but edits won't land.
            currentMsgId = null
          }
          segments.length = 0
          toolIndex.clear()
          editCount = 0
          return
        }
        const ok = await runEdit(renderPlain())
        if (ok) editCount++
      })
    }

    const scheduleEdit = () => {
      if (pendingTimer || finalizing || !hasEdit || currentMsgId == null) return
      const delay = editCount === 0 ? FIRST_EDIT_MS : SUBSEQUENT_EDIT_MS
      pendingTimer = setTimeout(flushEdit, delay)
    }

    // 4. Consume stream.
    const reader = selfStream.getReader()
    try {
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        const v = value as {
          type: string
          delta?: string
          textDelta?: string
          data?: { input_tokens?: number; output_tokens?: number; provider_id?: string; model_id?: string; system_prompt?: string; messages?: unknown[]; response?: string; tools?: string[]; adapter?: string; tool_id?: string; tool_call_id?: string }
          toolCallId?: string
          toolName?: string
        }

        if (v.type === 'text-delta' || v.type === 'text' || v.type === 'text-start') {
          const delta = v.delta ?? v.textDelta ?? ''
          appendText(delta)
          if (delta) scheduleEdit()
        } else if (
          v.type === 'tool-call' ||
          v.type === 'tool-input-start' ||
          v.type === 'tool-input-available' ||
          v.type === 'data-jiku-tool-start'
        ) {
          const id = v.toolCallId ?? `tool-${toolIndex.size}`
          const name = v.toolName ?? v.data?.tool_id ?? 'tool'
          pushTool(id, name)
          scheduleEdit()
        } else if (
          v.type === 'tool-result' ||
          v.type === 'tool-output-available' ||
          v.type === 'data-jiku-tool-end'
        ) {
          updateToolStatus(v.toolCallId ?? v.data?.tool_call_id, 'done')
          scheduleEdit()
        } else if (v.type === 'tool-error' || v.type === 'data-jiku-tool-error') {
          updateToolStatus(v.toolCallId, 'error')
          scheduleEdit()
        } else if (v.type === 'data-jiku-usage') {
          usageInput = v.data?.input_tokens ?? 0
          usageOutput = v.data?.output_tokens ?? 0
        } else if (v.type === 'data-jiku-meta') {
          providerId = v.data?.provider_id ?? providerId
          modelId = v.data?.model_id ?? modelId
        } else if (v.type === 'data-jiku-run-snapshot') {
          runSnapshot = v.data as RunSnapshot
        }
      }
    } finally {
      reader.releaseLock()
      observer.done()
    }

    // 5. Finalize. Wait for any pending debounced edit so it doesn't race
    //    the final send.
    finalizing = true
    if (pendingTimer) { clearTimeout(pendingTimer); pendingTimer = null }
    await editChain

    const hasContent = segments.some(s => (s.type === 'text' && s.content.trim() !== '') || (s.type === 'tools' && s.items.length > 0))
    const finalText = hasContent ? renderPlain() : '(no response)'

    let finalMsgId: number | null = currentMsgId
    if (hasEdit && currentMsgId != null) {
      const ok = await runEdit(finalText)
      if (!ok) {
        // Final edit failed (non-NOT_MODIFIED). Fall back to sending a fresh
        // message so the user sees SOMETHING — the stranded ⌛ stays but
        // that's recoverable with a later edit if the user retries.
        try {
          const queued = await queue.enqueue<{ id?: number } | undefined>(
            { chatId },
            () => client.sendText(peer, finalText, sendOpts) as Promise<{ id?: number } | undefined>,
            'send_message',
          )
          if (typeof queued.result?.id === 'number') finalMsgId = queued.result.id
        } catch (err) {
          this.con(ctx.connectorId)?.warn(`stream final fallback send failed: ${err instanceof Error ? err.message : String(err)}`)
        }
      }
    } else {
      // editMessage unavailable OR placeholder never landed. Just send once.
      try {
        const queued = await queue.enqueue<{ id?: number } | undefined>(
          { chatId },
          () => client.sendText(peer, finalText, sendOpts) as Promise<{ id?: number } | undefined>,
          'send_message',
        )
        if (typeof queued.result?.id === 'number') finalMsgId = queued.result.id
      } catch (err) {
        this.con(ctx.connectorId)?.warn(`stream no-edit final send failed: ${err instanceof Error ? err.message : String(err)}`)
      }
    }

    // 6. Log outbound + record usage. Snapshot uses the plain render so DB
    //    rows stay readable.
    const plainSnapshot = renderPlain()
    const refKeys = { message_id: String(finalMsgId ?? ''), chat_id: chatId }
    const sendResult: ConnectorSendResult = {
      success: finalMsgId != null,
      ref_keys: refKeys,
      raw_payload: { streamed: true, message_id: finalMsgId },
    }

    await ctx.logOutboundMessage({
      ref_keys: refKeys,
      content_snapshot: plainSnapshot,
      raw_payload: sendResult,
      status: finalMsgId != null ? 'sent' : 'failed',
    }).catch(() => null)
    await ctx.logOutboundEvent({
      event_type: 'send_message',
      ref_keys: refKeys,
      payload: { text: plainSnapshot, markdown: false, source: 'resolved_event_stream', tools: allTools().map(s => ({ name: s.name, status: s.status })) },
      raw_payload: sendResult,
      status: finalMsgId != null ? 'routed' : 'error',
    }).catch(() => null)

    if (usageInput > 0 || usageOutput > 0) {
      ctx.recordUsage({
        input_tokens: usageInput,
        output_tokens: usageOutput,
        provider: providerId,
        model: modelId,
        raw_system_prompt: runSnapshot?.system_prompt ?? null,
        raw_messages: runSnapshot?.messages ?? null,
        raw_response: runSnapshot?.response ?? plainSnapshot,
        active_tools: runSnapshot?.tools ?? null,
        agent_adapter: runSnapshot?.adapter ?? null,
      })
    }
  }

  /**
   * Userbot-exclusive action: forward with `drop_author` (hide sender + preserve
   * Premium animated custom_emoji). Phase 4 will register this as a proper
   * `connector_run_action` entry; for now it's a method other code can call.
   */
  async forwardDropAuthor(opts: { from_chat_id: string | number; message_ids: number[]; to_chat_id: string | number }): Promise<ConnectorSendResult> {
    if (!this.client) return { success: false, error: 'Userbot client not connected' }
    try {
      const res = await this.client.forwardMessagesById({
        fromChatId: opts.from_chat_id,
        messages: opts.message_ids,
        toChatId: opts.to_chat_id,
        noAuthor: true,
      })
      return { success: true, raw_payload: res }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      return { success: false, error: msg }
    }
  }

  /**
   * Userbot-exclusive: read full chat history past Bot API's 100-message cap.
   */
  async getChatHistory(peer: string | number, limit = 50, offsetId = 0): Promise<Array<Record<string, unknown>>> {
    if (!this.client) throw new Error('Userbot client not connected')
    return this.client.getHistory(peer, { limit, offsetId })
  }

  // ─── Forum topic auto-registration ──────────────────────────────────────
  //
  // Parity with TelegramBotAdapter.autoRegisterForumTopic (bot-adapter.ts:696).
  // On first sighting of a topic message, materialise a `connector_target`
  // row so the topic is rememberable + addressable in the Channels UI + by
  // name in outbound tools. UX: user sees "Bitorex → topic-17" show up
  // automatically and can rename/annotate it.
  //
  // Caveat: mtcute's inbound Message payload does NOT carry the forum topic
  // name (grammy bot surfaces it via `reply_to_message.forum_topic_created.name`;
  // mtcute exposes only `isForumTopic + threadId`). We use the fallback name
  // `topic-<threadId>` and leave `thread_title: null`. Enriching via
  // `client.getForumTopics(peer)` is a follow-up — it would add one RPC per
  // first-sighting and needs FLOOD_WAIT handling, so not free.

  private slugifyChannelTitle(title: string): string {
    return title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 50) || 'chat'
  }

  private async autoRegisterForumTopic(
    chatId: string,
    chatTitle: string | undefined,
    threadId: string,
    connectorId: string,
  ): Promise<void> {
    if (!this.projectId) return
    const chatSlug = this.slugifyChannelTitle(chatTitle ?? `chat-${chatId}`)
    const targetName = `${chatSlug}__topic-${threadId}`
    try {
      const existing = await getConnectorTargetByName(this.projectId, targetName, connectorId).catch(() => null)
      if (existing) return
      await createConnectorTarget({
        connector_id: connectorId,
        name: targetName,
        display_name: `${chatTitle ?? chatId} → topic-${threadId}`,
        description: `Auto-registered forum topic (userbot) — first seen ${new Date().toISOString()}. Rename via UI if needed.`,
        ref_keys: { chat_id: chatId, thread_id: threadId },
        scope_key: `group:${chatId}:topic:${threadId}`,
        metadata: {
          auto_registered: true,
          adapter: 'jiku.telegram.user',
          chat_title: chatTitle,
          thread_title: null,
          thread_id: threadId,
          registered_at: new Date().toISOString(),
        },
      })
      this.con(connectorId)?.info(`auto-registered topic target "${targetName}" (group:${chatId}:topic:${threadId})`)
    } catch (err) {
      this.con(connectorId)?.warn(`failed to auto-register topic target: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  // ─── Scope helpers (forum topic-aware) ─────────────────────────────────
  //
  // Parity with TelegramBotAdapter.computeScopeKey / targetFromScopeKey
  // (bot-adapter.ts:178-200). Must match the same `group:{chatId}:topic:{threadId}`
  // grammar so bindings + outbound routing are interchangeable between
  // bot and userbot for the same chat/topic.

  override computeScopeKey(event: { ref_keys: Record<string, string>; metadata?: Record<string, unknown> }): string | undefined {
    const chatId = event.ref_keys['chat_id']
    const chatType = event.metadata?.['chat_type'] as string | undefined
    const threadId = event.ref_keys['thread_id']
    if (!chatId) return undefined
    if (chatType === 'private') return undefined  // DM
    const base = `group:${chatId}`
    if (threadId) return `${base}:topic:${threadId}`
    return base
  }

  override targetFromScopeKey(scopeKey: string): ConnectorTarget | null {
    const parts = scopeKey.split(':')
    if (parts[0] !== 'group') return null
    const chatId = parts[1]
    if (!chatId) return null
    const ref_keys: Record<string, string> = { chat_id: chatId }
    const topicIdx = parts.indexOf('topic')
    if (topicIdx !== -1 && parts[topicIdx + 1]) {
      ref_keys['thread_id'] = parts[topicIdx + 1]!
    }
    return { ref_keys }
  }

  // ─── Plan 24 Phase 4 — Action registry ────────────────────────────────────

  override readonly actions: ConnectorAction[] = [
    {
      id: 'forward_message',
      name: 'Forward Message',
      description: 'Forward one or more messages from a source chat to a destination chat. With hide_sender:true (USERBOT-ONLY: works correctly), the "Forwarded from" header is suppressed AND animated Premium custom_emoji are preserved — Bot API copyMessage cannot do this.',
      params: {
        from_chat_id: { type: 'string', description: 'Source chat_id — the chat where the messages LIVE. For group messages, this is the group id (e.g. -100xxxxxxxxxx), NOT the sender user_id. The userbot must have interacted with this peer (received a message from / sent a message to) for the access_hash to be in cache.', required: true },
        to_chat_id: { type: 'string', description: 'Destination chat_id', required: true },
        message_ids: { type: 'string', description: 'Comma-separated NUMERIC Telegram message IDs to forward, e.g. "123,124,125". NOT UUIDs / connector_events.id.', required: true },
        hide_sender: { type: 'boolean', description: 'Hide the "Forwarded from" header AND preserve Premium custom_emoji animation. Default true on userbot.', required: false },
      },
    },
    {
      id: 'get_chat_history',
      name: 'Get Chat History',
      description: 'Read past N messages from a chat. Supports arbitrary offset (Bot API limited to ~100). USERBOT-ONLY.',
      params: {
        peer: { type: 'string', description: 'Chat ID, username, or invite link', required: true },
        limit: { type: 'number', description: 'Number of messages to fetch (default 50, max 200)', required: false },
        offset_id: { type: 'number', description: 'Start offset — fetch messages BEFORE this message_id (for pagination)', required: false },
      },
    },
    {
      id: 'get_dialogs',
      name: 'Get Dialogs',
      description: 'List all chats this account is currently in. USERBOT-ONLY.',
      params: {
        limit: { type: 'number', description: 'Max number of dialogs to return (default 30)', required: false },
      },
    },
    {
      id: 'set_typing',
      name: 'Set Typing',
      description: 'Show "typing…" indicator in a chat. USERBOT-ONLY (longer-running than Bot API).',
      params: {
        chat_id: { type: 'string', description: 'Chat to show typing in', required: true },
      },
    },
    {
      id: 'edit_message',
      name: 'Edit Message',
      description: 'Edit the text of a previously sent message.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        message_id: { type: 'string', description: 'Message ID', required: true },
        text: { type: 'string', description: 'New text', required: true },
        markdown: { type: 'boolean', description: 'Parse text as MarkdownV2. Mutually exclusive with `entities`.', required: false },
        entities: { type: 'array', description: 'Raw Telegram MessageEntity[] for the new text — preserves bold/italic/link/spoiler/custom_emoji. Custom_emoji animates when self-bot is Premium. Mutually exclusive with `markdown`.', required: false },
      },
    },
    {
      id: 'send_text',
      name: 'Send Text',
      description: 'Send a plain text message with optional entities (bold/italic/link/spoiler/custom_emoji). Use this when the text is stored in a DB (editable by AI later) rather than forwarded from an existing message. For custom_emoji animation, self-bot must be Premium. For forwarding an existing message, use `copy_message` instead.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        text: { type: 'string', description: 'Message text (Telegram cap: 4096 chars)', required: true },
        markdown: { type: 'boolean', description: 'Parse text as MarkdownV2. Mutually exclusive with `entities`.', required: false },
        entities: { type: 'array', description: 'Raw Telegram MessageEntity[] for the text — preserves bold/italic/link/spoiler/custom_emoji. Custom_emoji animates when self-bot is Premium. Mutually exclusive with `markdown`.', required: false },
        reply_to_message_id: { type: 'string', description: 'Message id in the same chat to reply to', required: false },
      },
    },
    // ─── Parity with TelegramBotAdapter ────────────────────────────────────
    {
      id: 'send_photo',
      name: 'Send Photo',
      description: 'Send a photo. Source = one of: `url` (public URL), `path` (project disk), `file_id` (a TDLib/Bot-API file_id string the userbot has seen before — instant reuse, no re-upload). Exactly ONE source param must be set.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        url: { type: 'string', description: 'Public URL of the photo (https://...). Mutually exclusive with `path` / `file_id`.', required: false },
        path: { type: 'string', description: 'Local path on the project virtual disk (e.g. "/assets/banner.jpg"). Mutually exclusive with `url` / `file_id`.', required: false },
        file_id: { type: 'string', description: 'File id / remote reference the userbot already has. Ideal for re-sending media from an earlier message without re-uploading. Mutually exclusive with `url` / `path`.', required: false },
        caption: { type: 'string', description: 'Caption text (Telegram cap: 1024 chars)', required: false },
        markdown: { type: 'boolean', description: 'Parse caption as MarkdownV2. Mutually exclusive with `caption_entities`.', required: false },
        caption_entities: { type: 'array', description: 'Raw Telegram MessageEntity[] for the caption — use to preserve bold/italic/link/spoiler/custom_emoji that markdown cannot express. When the self-bot account is Premium, custom_emoji entities ANIMATE in the delivered message. Mutually exclusive with `markdown`.', required: false },
      },
    },
    {
      id: 'send_document',
      name: 'Send Document',
      description: 'Send a file (PDFs, archives, generic files). Source = one of: `url` / `path` / `file_id`. Exactly ONE must be set.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        url: { type: 'string', description: 'Public URL of the document. Mutually exclusive with `path` / `file_id`.', required: false },
        path: { type: 'string', description: 'Local path on the project disk. Mutually exclusive with `url` / `file_id`.', required: false },
        file_id: { type: 'string', description: 'File id the userbot has seen before. Mutually exclusive with `url` / `path`.', required: false },
        filename: { type: 'string', description: 'Override file name shown in Telegram', required: false },
        caption: { type: 'string', description: 'Caption text', required: false },
        markdown: { type: 'boolean', description: 'Parse caption as MarkdownV2. Mutually exclusive with `caption_entities`.', required: false },
        caption_entities: { type: 'array', description: 'Raw Telegram MessageEntity[] for the caption — preserves bold/italic/link/spoiler/custom_emoji. Custom_emoji animates when self-bot is Premium. Mutually exclusive with `markdown`.', required: false },
      },
    },
    {
      id: 'send_video',
      name: 'Send Video',
      description: 'Send a single video. Source = one of: `url` / `path` / `file_id`. Exactly ONE must be set. For sending MULTIPLE videos as one album, use `send_media_group` instead.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        url: { type: 'string', description: 'Public URL of the video (https://...). Mutually exclusive with `path` / `file_id`.', required: false },
        path: { type: 'string', description: 'Local path on the project virtual disk (e.g. "/videos/demo.mp4"). Mutually exclusive with `url` / `file_id`.', required: false },
        file_id: { type: 'string', description: 'File id the userbot has seen before. Mutually exclusive with `url` / `path`.', required: false },
        caption: { type: 'string', description: 'Caption text (Telegram cap: 1024 chars)', required: false },
        markdown: { type: 'boolean', description: 'Parse caption as MarkdownV2. Mutually exclusive with `caption_entities`.', required: false },
        caption_entities: { type: 'array', description: 'Raw Telegram MessageEntity[] for the caption — preserves bold/italic/link/spoiler/custom_emoji. Custom_emoji animates when self-bot is Premium. Mutually exclusive with `markdown`.', required: false },
      },
    },
    {
      id: 'send_media_group',
      name: 'Send Media Group (Album)',
      description: 'Send multiple photos, videos, or documents as a single album. Photos and videos can be mixed (max 10 items). Only the first item caption is shown prominently. Each item\'s source = one of `url` / `path` / `file_id`.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        media: { type: 'array', description: 'Array of media items: { type: "photo"|"video"|"document", url?: string, path?: string, file_id?: string, caption?: string, caption_markdown?: boolean, caption_entities?: MessageEntity[] }. Max 10 items. Each item must have exactly ONE of `url` / `path` / `file_id`. `caption_entities` preserves bold/italic/link/custom_emoji (animated when self-bot is Premium); mutually exclusive with `caption_markdown` per item.', required: true },
      },
    },
    {
      id: 'copy_message',
      name: 'Copy Message',
      description: 'Copy a message to another chat WITHOUT a "Forwarded from" header. Userbot delegates to forward_message with hide_sender:true. IMPORTANT: from_chat_id is the chat where the message LIVES (not the sender — for group messages this is the group id, e.g. -100xxxxxxxxxx). message_id is the numeric Telegram message id (e.g. 12345), NOT a connector_events.id UUID.',
      params: {
        from_chat_id: { type: 'string', description: 'Source chat_id (chat where the message lives — for group messages, the group id, NOT the sender user_id)', required: true },
        to_chat_id: { type: 'string', description: 'Destination chat_id', required: true },
        message_id: { type: 'string', description: 'Numeric Telegram message_id (e.g. "12345"). NOT a UUID or connector_events.id.', required: true },
      },
    },
    {
      id: 'get_chat_info',
      name: 'Get Chat Info',
      description: 'Fetch chat metadata (title, type, member count, description, invite_link if any).',
      params: {
        chat_id: { type: 'string', description: 'Chat ID, username, or invite link', required: true },
      },
    },
    // ─── Userbot-EXCLUSIVE (Bot API does NOT support these) ───────────────
    {
      id: 'mark_read',
      name: 'Mark Read',
      description: 'Mark messages in a chat as read up to a given message_id. USERBOT-ONLY — bots cannot mark-read on behalf of users. Useful when the agent has consumed inbound silently and wants to clear unread state for the human owner.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        max_id: { type: 'number', description: 'Mark all messages up to and including this id as read', required: false },
      },
    },
    {
      id: 'search_messages',
      name: 'Search Messages',
      description: 'Search messages globally or within a chat by text. USERBOT-ONLY.',
      params: {
        query: { type: 'string', description: 'Search text', required: true },
        chat_id: { type: 'string', description: 'Limit search to one chat (omit for global search)', required: false },
        limit: { type: 'number', description: 'Max results (default 30)', required: false },
      },
    },
    {
      id: 'get_user_info',
      name: 'Get User Info',
      description: 'Detailed user profile (full name, bio, photos, common chats). USERBOT-ONLY.',
      params: {
        user: { type: 'string', description: 'User id, @username, or +phone', required: true },
      },
    },
  ]

  /** Snapshot of the userbot queue — surfaced via `connector_get_queue_status`. */
  getQueueStatus(connectorId?: string) {
    const queue = this.queueFor(connectorId)
    return queue.status()
  }

  override async runAction(actionId: string, params: Record<string, unknown>, connectorId?: string): Promise<unknown> {
    // Multi-tenant: resolve client + queue for the right credential.
    const client = this.clientFor(connectorId)
    const queue = this.queueFor(connectorId)
    if (!client) throw new Error('Userbot client not connected for this connector')
    const c = client as MtcuteClient & {
      getDialogs?: (opts?: { limit?: number }) => Promise<Array<Record<string, unknown>>>
      sendTyping?: (peer: string | number | bigint, status?: string) => Promise<unknown>
      editMessage?: (opts: { chatId: string | number | bigint; message: number; text: string; parseMode?: string }) => Promise<unknown>
    }

    const peerOf = (raw: unknown): string | number => {
      const s = String(raw ?? '')
      if (!s) throw new Error('Missing peer / chat_id')
      return /^-?\d+$/.test(s) ? Number(s) : s
    }

    const idsOf = (raw: unknown): number[] => String(raw ?? '').split(',').map(s => Number(s.trim())).filter(n => Number.isFinite(n))

    // Every action goes through the queue. Scope is chat-level when
    // the action targets a specific chat, '_global' for session-wide ones.
    const enqueue = <T>(scope: { chatId: string | '_global' }, fn: () => Promise<T>) =>
      queue.enqueue(scope, fn, actionId)

    try {
      if (actionId === 'forward_message') {
        const hideSender = params['hide_sender'] !== false
        const messageIds = idsOf(params['message_ids'])
        if (messageIds.length === 0) {
          return { success: false, code: 'INVALID_MESSAGE_ID', error: `forward_message requires numeric message_ids; received "${String(params['message_ids'])}". Telegram message ids are integers (e.g. 12345) — not UUIDs or event ids.` }
        }
        const queued = await enqueue({ chatId: String(params['from_chat_id']) }, () => c.forwardMessagesById({
          fromChatId: peerOf(params['from_chat_id']),
          messages: messageIds,
          toChatId: peerOf(params['to_chat_id']),
          noAuthor: hideSender,
        }))
        return { success: true, hide_sender: hideSender, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'get_chat_history') {
        const limit = Math.min(Number(params['limit'] ?? 50), 200)
        const offsetId = Number(params['offset_id'] ?? 0)
        const queued = await enqueue({ chatId: String(params['peer']) }, () => c.getHistory(peerOf(params['peer']), { limit, offsetId }))
        return { success: true, count: queued.result.length, messages: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'get_dialogs') {
        if (!c.getDialogs) return { success: false, error: 'mtcute client does not expose getDialogs in this build' }
        const limit = Math.min(Number(params['limit'] ?? 30), 200)
        const queued = await enqueue({ chatId: '_global' }, () => c.getDialogs!({ limit }))
        return { success: true, count: queued.result.length, dialogs: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'set_typing') {
        if (!c.sendTyping) return { success: false, error: 'mtcute client does not expose sendTyping in this build' }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => c.sendTyping!(peerOf(params['chat_id']), 'typing'))
        return { success: true, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'edit_message') {
        if (!c.editMessage) return { success: false, error: 'mtcute client does not expose editMessage in this build' }
        const text = String(params['text'] ?? '')
        const useMd = params['markdown'] === true
        const entities = params['entities'] as unknown[] | undefined
        if (useMd && entities) return { success: false, error: 'markdown and entities are mutually exclusive', hint: 'Pick one: markdown (convenience) or entities (precise control, required for custom_emoji).' }
        const finalText = useMd ? telegramifyMarkdown(text, 'escape') : text
        // mtcute v0.27: `text` is InputText = string | TextWithEntities.
        // When entities are provided, pass `{ text, entities }` object instead
        // of string. parseMode becomes nonsensical in that case.
        const textArg: unknown = entities ? { text: finalText, entities } : finalText
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => c.editMessage!({
          chatId: peerOf(params['chat_id']),
          message: Number(params['message_id']),
          text: textArg as string,
          parseMode: useMd ? 'MarkdownV2' : undefined,
        }))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'send_text') {
        const text = String(params['text'] ?? '')
        if (!text) return { success: false, error: 'send_text requires non-empty `text`' }
        const useMd = params['markdown'] === true
        const entities = params['entities'] as unknown[] | undefined
        if (useMd && entities) return { success: false, error: 'markdown and entities are mutually exclusive', hint: 'Pick one: markdown (convenience) or entities (precise control, required for custom_emoji).' }
        const finalText = useMd ? telegramifyMarkdown(text, 'escape') : text
        // mtcute v0.27 `sendText` accepts `InputText = string | TextWithEntities`.
        // Pass { text, entities } to preserve custom_emoji + formatting.
        const textArg: unknown = entities ? { text: finalText, entities } : finalText
        const opts: Record<string, unknown> = {}
        if (useMd) opts['parseMode'] = 'MarkdownV2'
        if (params['reply_to_message_id']) opts['replyTo'] = Number(params['reply_to_message_id'])
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () =>
          client.sendText(peerOf(params['chat_id']) as number, textArg as string, opts) as Promise<{ id?: number; chat?: { id?: number | bigint } } | undefined>
        )
        const res = queued.result
        return { success: true, message_id: res?.id ? String(res.id) : undefined, chat_id: res?.chat?.id ? String(res.chat.id) : undefined, result: res, delay_ms_applied: queued.delay_ms_applied }
      }

      // ─── Parity actions ──────────────────────────────────────────────────
      const cExt = c as MtcuteClient & {
        sendMedia?: (chatId: string | number | bigint, media: unknown, opts?: Record<string, unknown>) => Promise<unknown>
        sendMediaGroup?: (chatId: string | number | bigint, medias: unknown[], opts?: Record<string, unknown>) => Promise<unknown>
        sendPhoto?: (chatId: string | number | bigint, photo: unknown, opts?: Record<string, unknown>) => Promise<unknown>
        sendVideo?: (chatId: string | number | bigint, video: unknown, opts?: Record<string, unknown>) => Promise<unknown>
        sendDocument?: (chatId: string | number | bigint, document: unknown, opts?: Record<string, unknown>) => Promise<unknown>
        readHistory?: (chatId: string | number | bigint, opts?: { maxId?: number }) => Promise<unknown>
        searchGlobal?: (query: string, opts?: { limit?: number }) => Promise<Array<Record<string, unknown>>>
        searchMessages?: (opts: { chatId?: string | number | bigint; query: string; limit?: number }) => Promise<Array<Record<string, unknown>>>
        getFullUser?: (userId: string | number | bigint) => Promise<Record<string, unknown>>
        getChat?: (chatId: string | number | bigint) => Promise<Record<string, unknown>>
        resolvePeer?: (peer: string | number | bigint) => Promise<Record<string, unknown>>
      }

      // Shared helper: resolve a media item's source (`url` | `path` | `file_id`)
      // to a value mtcute's sendMedia/sendPhoto/etc. accepts. mtcute's
      // `UploadFileLike` accepts a bare string that is a TDLib / Bot-API
      // compatible file_id — we pass URL and file_id through as strings and
      // decode `__b64__:` filesystem paths to a Buffer.
      const resolveMediaInput = async (item: { url?: string; path?: string; file_id?: string }): Promise<{ value: unknown; err?: string }> => {
        const count = [item.url, item.path, item.file_id].filter(Boolean).length
        if (count === 0) return { value: undefined, err: 'each item requires exactly one of `url` / `path` / `file_id`' }
        if (count > 1) return { value: undefined, err: 'each item requires exactly one of `url` / `path` / `file_id` — not multiple' }
        if (item.url) return { value: item.url }
        if (item.file_id) return { value: item.file_id }
        if (!this.projectId) return { value: undefined, err: 'No active project for path resolution' }
        const fs = await getFilesystemService(this.projectId)
        if (!fs) return { value: undefined, err: 'Filesystem not configured for this project' }
        const file = await fs.read(item.path!)
        return {
          value: file.content.startsWith('__b64__:')
            ? Buffer.from(file.content.replace('__b64__:', ''), 'base64')
            : Buffer.from(file.content, 'utf-8'),
        }
      }

      if (actionId === 'send_photo') {
        const url = params['url'] as string | undefined
        const path = params['path'] as string | undefined
        const file_id = params['file_id'] as string | undefined
        const send = cExt.sendPhoto ?? cExt.sendMedia
        if (!send) return { success: false, error: 'mtcute build does not expose sendPhoto / sendMedia' }
        const caption = params['caption'] as string | undefined
        const useMd = params['markdown'] === true
        const entities = params['caption_entities'] as unknown[] | undefined
        if (useMd && entities) return { success: false, error: 'markdown and caption_entities are mutually exclusive', hint: 'Pick one: markdown (convenience) or caption_entities (precise control, required for custom_emoji).' }
        const opts: Record<string, unknown> = {}
        if (caption) opts['caption'] = useMd ? telegramifyMarkdown(caption, 'escape') : caption
        if (caption && useMd) opts['parseMode'] = 'MarkdownV2'
        if (entities) opts['entities'] = entities
        const resolved = await resolveMediaInput({ url, path, file_id })
        if (resolved.err) return { success: false, error: resolved.err }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => send.call(cExt, peerOf(params['chat_id']), resolved.value, opts))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'send_document') {
        const url = params['url'] as string | undefined
        const path = params['path'] as string | undefined
        const file_id = params['file_id'] as string | undefined
        const send = cExt.sendDocument ?? cExt.sendMedia
        if (!send) return { success: false, error: 'mtcute build does not expose sendDocument / sendMedia' }
        const caption = params['caption'] as string | undefined
        const useMd = params['markdown'] === true
        const entities = params['caption_entities'] as unknown[] | undefined
        if (useMd && entities) return { success: false, error: 'markdown and caption_entities are mutually exclusive', hint: 'Pick one: markdown (convenience) or caption_entities (precise control, required for custom_emoji).' }
        const opts: Record<string, unknown> = {}
        if (caption) opts['caption'] = useMd ? telegramifyMarkdown(caption, 'escape') : caption
        if (caption && useMd) opts['parseMode'] = 'MarkdownV2'
        if (entities) opts['entities'] = entities
        if (params['filename']) opts['fileName'] = String(params['filename'])
        const resolved = await resolveMediaInput({ url, path, file_id })
        if (resolved.err) return { success: false, error: resolved.err }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => send.call(cExt, peerOf(params['chat_id']), resolved.value, opts))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'send_video') {
        const url = params['url'] as string | undefined
        const path = params['path'] as string | undefined
        const file_id = params['file_id'] as string | undefined
        // mtcute: prefer sendVideo; fall back to sendMedia with explicit
        // `type: 'video'` since `sendMedia` with a raw buffer cannot tell
        // "video file" from "document" otherwise.
        const useSendMedia = !cExt.sendVideo && !!cExt.sendMedia
        if (!cExt.sendVideo && !cExt.sendMedia) {
          return { success: false, error: 'mtcute build exposes neither sendVideo nor sendMedia' }
        }
        const caption = params['caption'] as string | undefined
        const useMd = params['markdown'] === true
        const entities = params['caption_entities'] as unknown[] | undefined
        if (useMd && entities) return { success: false, error: 'markdown and caption_entities are mutually exclusive', hint: 'Pick one: markdown (convenience) or caption_entities (precise control, required for custom_emoji).' }
        const opts: Record<string, unknown> = {}
        if (caption) opts['caption'] = useMd ? telegramifyMarkdown(caption, 'escape') : caption
        if (caption && useMd) opts['parseMode'] = 'MarkdownV2'
        if (entities) opts['entities'] = entities
        const resolved = await resolveMediaInput({ url, path, file_id })
        if (resolved.err) return { success: false, error: resolved.err }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => {
          if (useSendMedia) {
            return cExt.sendMedia!.call(cExt, peerOf(params['chat_id']), { type: 'video', file: resolved.value, ...opts }, {})
          }
          return cExt.sendVideo!.call(cExt, peerOf(params['chat_id']), resolved.value, opts)
        })
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'send_media_group') {
        if (!cExt.sendMediaGroup) {
          return { success: false, error: 'mtcute build does not expose sendMediaGroup' }
        }
        const items = params['media'] as Array<{ type: 'photo' | 'video' | 'document'; url?: string; path?: string; file_id?: string; caption?: string; caption_markdown?: boolean; caption_entities?: unknown[] }> | undefined
        if (!Array.isArray(items) || items.length === 0) {
          return { success: false, error: 'send_media_group requires a non-empty `media` array' }
        }
        if (items.length > 10) {
          return { success: false, error: 'Telegram albums accept at most 10 items' }
        }
        // Build `InputMediaLike[]` — each item has { type, file, caption?, parseMode?, entities? }.
        const medias: unknown[] = []
        for (let i = 0; i < items.length; i++) {
          const it = items[i]!
          if (!['photo', 'video', 'document'].includes(it.type)) {
            return { success: false, error: `media[${i}].type must be one of "photo" | "video" | "document" (got "${it.type}")` }
          }
          if (it.caption_markdown && it.caption_entities) {
            return { success: false, error: `media[${i}]: caption_markdown and caption_entities are mutually exclusive`, hint: 'Pick one per item: caption_markdown (convenience) or caption_entities (precise control, required for custom_emoji).' }
          }
          const resolved = await resolveMediaInput(it)
          if (resolved.err) return { success: false, error: `media[${i}]: ${resolved.err}` }
          const entry: Record<string, unknown> = { type: it.type, file: resolved.value }
          if (it.caption) {
            entry['caption'] = it.caption_markdown ? telegramifyMarkdown(it.caption, 'escape') : it.caption
            if (it.caption_markdown) entry['parseMode'] = 'MarkdownV2'
          }
          if (it.caption_entities) entry['entities'] = it.caption_entities
          medias.push(entry)
        }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () =>
          cExt.sendMediaGroup!.call(cExt, peerOf(params['chat_id']), medias, {})
        )
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied, count: medias.length }
      }

      if (actionId === 'copy_message') {
        // Userbot has no native "copy" — forward with hide_sender:true gives the
        // same UX (no header) but with custom_emoji preservation as bonus.
        const msgId = Number(params['message_id'])
        if (!Number.isFinite(msgId) || msgId <= 0) {
          return { success: false, code: 'INVALID_MESSAGE_ID', error: `copy_message requires a numeric message_id; received "${String(params['message_id'])}". Telegram message ids are integers (e.g. 12345) — not UUIDs or event ids.` }
        }
        const queued = await enqueue({ chatId: String(params['from_chat_id']) }, () => c.forwardMessagesById({
          fromChatId: peerOf(params['from_chat_id']),
          messages: [msgId],
          toChatId: peerOf(params['to_chat_id']),
          noAuthor: true,
        }))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'get_chat_info') {
        const get = cExt.getChat ?? cExt.resolvePeer
        if (!get) return { success: false, error: 'mtcute build does not expose getChat / resolvePeer' }
        const queued = await enqueue({ chatId: '_global' }, () => get.call(cExt, peerOf(params['chat_id'])))
        return { success: true, chat: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      // ─── Userbot-EXCLUSIVE ───────────────────────────────────────────────
      if (actionId === 'mark_read') {
        if (!cExt.readHistory) return { success: false, error: 'mtcute build does not expose readHistory' }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => cExt.readHistory!(peerOf(params['chat_id']), {
          maxId: params['max_id'] !== undefined ? Number(params['max_id']) : undefined,
        }))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'search_messages') {
        const query = String(params['query'] ?? '')
        if (!query) return { success: false, error: 'query required' }
        const limit = Math.min(Number(params['limit'] ?? 30), 100)
        const chatId = params['chat_id'] as string | undefined
        if (chatId && cExt.searchMessages) {
          const queued = await enqueue({ chatId: String(chatId) }, () => cExt.searchMessages!({
            chatId: peerOf(chatId), query, limit,
          }))
          return { success: true, count: queued.result.length, messages: queued.result, delay_ms_applied: queued.delay_ms_applied }
        }
        if (!chatId && cExt.searchGlobal) {
          const queued = await enqueue({ chatId: '_global' }, () => cExt.searchGlobal!(query, { limit }))
          return { success: true, count: queued.result.length, messages: queued.result, delay_ms_applied: queued.delay_ms_applied }
        }
        return { success: false, error: 'mtcute build does not expose searchMessages / searchGlobal' }
      }

      if (actionId === 'get_user_info') {
        if (!cExt.getFullUser) return { success: false, error: 'mtcute build does not expose getFullUser' }
        const queued = await enqueue({ chatId: '_global' }, () => cExt.getFullUser!(peerOf(params['user'])))
        return { success: true, user: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      return { success: false, error: `Unknown action: ${actionId}` }
    } catch (err) {
      return mapQueueError(err)
    }
  }

  override async sendTyping(target: ConnectorTarget): Promise<void> {
    const chatId = target.ref_keys['chat_id']
    if (!chatId || !this.client) return
    const c = this.client as MtcuteClient & { sendTyping?: (peer: string | number | bigint, status?: string) => Promise<unknown> }
    if (c.sendTyping) {
      await c.sendTyping(/^-?\d+$/.test(chatId) ? Number(chatId) : chatId, 'typing').catch(() => {})
    }
  }
}

export const telegramUserAdapter = new TelegramUserAdapter()
export { TelegramUserAdapter }

/**
 * Extract reply context from a mtcute Message into a plain JSON-safe object
 * suitable for `event.metadata.reply_to`. Uses duck typing because mtcute's
 * RepliedMessageInfo is a class with getters that don't survive JSON.
 */
function extractMtcuteReply(m: { replyToMessage?: unknown }): { reply_to?: Record<string, unknown> } {
  const r = m.replyToMessage as
    | {
        id?: number | null
        origin?: string
        chat?: { id?: number | bigint } | null
        sender?: { id?: number | bigint; username?: string; firstName?: string; displayName?: string } | null
        quoteText?: string
        isQuote?: boolean
        threadId?: number | null
      }
    | null
    | undefined
  if (!r || typeof r !== 'object') return {}
  const id = r.id ?? null
  if (id === null && !r.sender) return {}  // nothing useful
  const reply_to: Record<string, unknown> = {
    origin: r.origin ?? 'same_chat',
    is_quote: r.isQuote === true,
  }
  if (id !== null) reply_to['message_id'] = String(id)
  if (r.chat?.id != null) reply_to['chat_id'] = String(r.chat.id)
  if (r.threadId != null) reply_to['thread_id'] = String(r.threadId)
  if (r.sender) {
    reply_to['sender'] = {
      id: r.sender.id != null ? String(r.sender.id) : null,
      username: r.sender.username ?? null,
      display_name: r.sender.displayName ?? r.sender.firstName ?? null,
    }
  }
  if (r.quoteText) reply_to['quote_text'] = r.quoteText
  return { reply_to }
}
