import { z } from 'zod'
import { ConnectorAdapter } from '@jiku/kit'
import type {
  ConnectorAction, ConnectorEvent, ConnectorContext, ConnectorTarget, ConnectorContent,
  ConnectorSendResult,
  ConnectorSetupSessionState, ConnectorSetupStepResult,
} from '@jiku/types'
import telegramifyMarkdown from 'telegramify-markdown'
import { TelegramClient } from '@mtcute/bun'
import { logConnectorEvent } from '@jiku-studio/db'
import { getFilesystemService } from '../../../apps/studio/server/src/filesystem/service.ts'
import { UserbotQueue, type UserbotQueuePolicy } from './userbot-queue.ts'
import { REACTIVATE_WAIT_MS } from './shared/constants.ts'
import { lastDeactivateByConnector } from './shared/queues.ts'
import { mapQueueError } from './shared/error-mapper.ts'
import type { PluginConsoleAPI, PluginConsoleLogger } from '@jiku-plugin/studio'

/** Console id for a given Telegram user (self-bot) connector instance. */
export function userConsoleId(connectorId: string): string {
  return `jiku.telegram.user:connector:${connectorId}`
}

// `unknown` typing for the mtcute client because the plugin file would need
// every mtcute type imported just to satisfy TS. Type-aliased to the real
// TelegramClient class statically imported above.
type MtcuteClient = TelegramClient

class TelegramUserAdapter extends ConnectorAdapter {
  readonly id = 'jiku.telegram.user'
  readonly displayName = 'Telegram User (Self-Bot)'
  readonly credentialAdapterId = 'telegram-user'
  override readonly credentialDisplayName = 'Telegram User (Self-Bot)'
  readonly refKeys = ['message_id', 'chat_id', 'thread_id', 'user_id']
  readonly supportedEvents = ['message', 'reaction', 'unreaction', 'edit', 'delete'] as const

  override readonly requiresInteractiveSetup = true

  override readonly credentialSchema = z.object({
    // Required user inputs from my.telegram.org. api_id + api_hash encrypted
    // (auth credential pair). phone_number kept in plain metadata — it's
    // user-facing identifier, useful in UI badges + searchable, and on its
    // own not enough to impersonate.
    api_id: z.string().min(1).describe('secret|API ID from my.telegram.org'),
    api_hash: z.string().min(1).describe('secret|API Hash from my.telegram.org'),
    phone_number: z.string().min(1).describe('Phone number with country code, e.g. +628123456789'),
    // Auto-filled by the setup wizard. session_string IS a full account token
    // (equivalent to bot_token) — stays encrypted. The other three are pure
    // display / metadata, no encryption needed.
    session_string: z.string().optional().describe('secret|Session (auto-generated by Setup wizard, do not edit)'),
    user_id: z.string().optional().describe('Logged-in user ID (auto)'),
    username: z.string().optional().describe('Username (auto)'),
    is_premium: z.string().optional().describe('Premium account (auto)'),
  })

  /**
   * Per-wizard mtcute clients. Keyed by `setup_session_id`. Each entry is the
   * client we stood up for `request_code` and re-use across `verify_code` /
   * `verify_password`. Cleared on completion or wizard cancel.
   *
   * NOT used at runtime — the runtime client lives in `this.client` and is
   * scoped to one credential.
   */
  private setupClients = new Map<string, MtcuteClient>()

  // ─── Multi-tenant per-credential state ────────────────────────────────────
  //
  // Same fix as TelegramBotAdapter: scalar state was a multi-tenant data leak
  // when 2+ userbot credentials activated in one process — second activate
  // overwrote first's `client/queue/myUserId/etc`. Now everything per-credential
  // lives in `userInstances` keyed by connectorId. Scalar fields kept as
  // legacy fallback (ditto `botFor()` pattern).
  //
  // queue is per-instance because Plan §8b's quotas (20/min global, etc.) are
  // PER-SESSION — sharing one queue across credentials would let one session's
  // burst eat into another's quota.

  private userInstances = new Map<string, {
    client: MtcuteClient
    projectId: string
    connectorId: string
    myUserId: string | null
    myUsername: string | null
    myIsPremium: boolean
    queue: UserbotQueue
    activatedAt: number
  }>()

  private clientFor(connectorId: string | null | undefined): MtcuteClient | null {
    if (connectorId) {
      const inst = this.userInstances.get(connectorId)
      if (inst) return inst.client
      return null
    }
    if (this.userInstances.size === 0) return this.client
    if (this.userInstances.size > 1) {
      console.warn(`[telegram.user] clientFor() called WITHOUT connector_id while ${this.userInstances.size} credentials active — defaulting to legacy fallback. Multi-tenant leak risk.`)
    }
    return this.client
  }

  private queueFor(connectorId: string | null | undefined): UserbotQueue {
    if (connectorId) {
      const inst = this.userInstances.get(connectorId)
      if (inst) return inst.queue
    }
    // Legacy fallback — single global queue for code paths not yet updated.
    return this.queue
  }

  private consoleApi: PluginConsoleAPI | null = null
  attachConsole(api: PluginConsoleAPI) { this.consoleApi = api }
  private con(connectorId: string | null | undefined): PluginConsoleLogger | null {
    if (!this.consoleApi || !connectorId) return null
    return this.consoleApi.get(userConsoleId(connectorId), `Telegram User ${connectorId.slice(0, 8)}`)
  }

  // Legacy scalar state (kept as fallback for single-tenant + getter-style reads).
  private client: TelegramClient | null = null
  private projectId: string | null = null
  private connectorId: string | null = null
  private myUserId: string | null = null
  /**
   * Legacy fallback queue. Active credentials get their OWN queue inside
   * `userInstances`. This scalar is only used when a code path doesn't pass
   * connectorId (deprecated — should be eliminated).
   */
  private queue = new UserbotQueue()

  override getSetupSpec() {
    return {
      title: 'Telegram User Account Setup',
      intro: 'You will receive a one-time code on your Telegram app. If you have 2FA enabled, the wizard will ask for your password after the code.',
      steps: [
        {
          id: 'request_code',
          title: 'Send verification code',
          description: 'Telegram will send a one-time code to your phone (via SMS or the Telegram app).',
          inputs: [],
        },
        {
          id: 'verify_code',
          title: 'Enter verification code',
          description: 'Enter the code Telegram just sent to your account.',
          inputs: [
            { name: 'code', type: 'string' as const, required: true, secret: false, label: 'OTP code', placeholder: '12345' },
          ],
        },
        {
          id: 'verify_password',
          title: 'Enter 2FA password',
          description: 'Your account has two-factor authentication enabled.',
          conditional: true,
          inputs: [
            { name: 'password', type: 'string' as const, required: true, secret: true, label: '2FA password' },
          ],
        },
      ],
    }
  }

  override async runSetupStep(stepId: string, input: Record<string, unknown>, state: ConnectorSetupSessionState): Promise<ConnectorSetupStepResult> {
    const fields = state.credential_fields ?? {}
    const apiIdRaw = fields['api_id']
    const apiHash = fields['api_hash']
    const phone = fields['phone_number']
    if (!apiIdRaw || !apiHash || !phone) {
      return { ok: false, error: 'Missing api_id, api_hash, or phone_number on the credential. Save those fields first, then re-run setup.' }
    }
    const apiId = Number(apiIdRaw)
    if (!Number.isFinite(apiId)) {
      return { ok: false, error: 'api_id must be numeric. Get it from my.telegram.org → API Development.' }
    }

    if (stepId === 'request_code') {
      try {
        // const { TelegramClient } = await import('@mtcute/bun') as { TelegramClient: new (opts: { apiId: number; apiHash: string; storage?: string }) => MtcuteClient }
        const client = new TelegramClient({ apiId, apiHash })
        await client.connect()
        const sent = await client.sendCode({ phone })
        // Stash phone_code_hash + client until the user enters the code.
        state.scratch['phone_code_hash'] = sent.phoneCodeHash
        this.setupClients.set(state.session_id, client)
        return { ok: true, next_step: 'verify_code', ui_message: 'Code sent. Check your Telegram app or SMS.' }
      } catch (err) {
        return {
          ok: false,
          error: err instanceof Error ? err.message : String(err),
          hint: 'Verify api_id, api_hash, and phone_number are correct. Phone needs country code (e.g. +628123…).',
        }
      }
    }

    if (stepId === 'verify_code') {
      const client = this.setupClients.get(state.session_id)
      if (!client) {
        return { ok: false, error: 'Setup session expired or `request_code` was never run. Start over from step 1.' }
      }
      const code = String(input['code'] ?? '').trim()
      if (!code) return { ok: false, error: 'OTP code is required.', retry_step: 'verify_code' }
      const phoneCodeHash = String(state.scratch['phone_code_hash'] ?? '')
      try {
        await client.signIn({ phone, phoneCodeHash, phoneCode: code })
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        if (msg.includes('SESSION_PASSWORD_NEEDED')) {
          return { ok: true, next_step: 'verify_password', ui_message: '2FA enabled. Enter your password.' }
        }
        if (msg.includes('PHONE_CODE_INVALID') || msg.includes('PHONE_CODE_EXPIRED')) {
          return { ok: false, error: msg, hint: 'OTP code wrong or expired. Re-check the code and try again.', retry_step: 'verify_code' }
        }
        return { ok: false, error: msg }
      }
      return this.finalizeLogin(client, state)
    }

    if (stepId === 'verify_password') {
      const client = this.setupClients.get(state.session_id)
      if (!client) {
        return { ok: false, error: 'Setup session expired. Start over.' }
      }
      const password = String(input['password'] ?? '')
      if (!password) return { ok: false, error: '2FA password is required.', retry_step: 'verify_password' }
      try {
        await client.checkPassword(password)
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        if (msg.includes('PASSWORD_HASH_INVALID')) {
          return { ok: false, error: msg, hint: 'Wrong 2FA password. Try again.', retry_step: 'verify_password' }
        }
        return { ok: false, error: msg }
      }
      return this.finalizeLogin(client, state)
    }

    return { ok: false, error: `Unknown step: ${stepId}` }
  }

  private async finalizeLogin(client: MtcuteClient, state: ConnectorSetupSessionState): Promise<ConnectorSetupStepResult> {
    try {
      const me = await client.getMe()
      // mtcute exposes session export under different names depending on build
      // (`exportSession` in some versions, `exportStringSession` in others).
      // Try in order; first non-empty result wins. Fail loudly if none yields
      // a string — silent empty session was the bug that made onActivate
      // throw "No session_string" right after a "successful" wizard.
      const c = client as MtcuteClient & {
        exportSession?: () => Promise<string> | string
        exportStringSession?: () => Promise<string> | string
      }
      let session: string | undefined
      if (typeof c.exportSession === 'function') {
        session = await c.exportSession()
      }
      if (!session && typeof c.exportStringSession === 'function') {
        session = await c.exportStringSession()
      }
      console.log(`[telegram.user] finalizeLogin: me=@${me.username ?? me.id} (id=${me.id}, premium=${!!me.isPremium}); session_len=${session?.length ?? 0}`)
      if (!session || typeof session !== 'string' || session.length === 0) {
        return {
          ok: false,
          error: 'mtcute did not return a session string. Tried `exportSession()` and `exportStringSession()` — both returned empty/null. Check @mtcute/bun version installed; this build may use a different export method.',
          hint: 'Run `bun pm ls @mtcute/bun` to confirm version. The adapter expects v0.27+ semantics.',
        }
      }
      try { await client.disconnect() } catch { /* best-effort */ }
      this.setupClients.delete(state.session_id)
      return {
        ok: true,
        complete: true,
        fields: {
          session_string: session,
          user_id: String(me.id),
          username: me.username ?? '',
          is_premium: me.isPremium ? 'true' : 'false',
        },
        ui_message: `Logged in as @${me.username ?? me.id} (${me.isPremium ? 'Premium' : 'Free'}). Setup complete — credential is now ready to activate.`,
      }
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) }
    }
  }

  // ─── Runtime ──────────────────────────────────────────────────────────────

  override async onActivate(ctx: ConnectorContext): Promise<void> {
    this.con(ctx.connectorId)?.info('Userbot activating', { project_id: ctx.projectId })
    const session = ctx.fields['session_string']
    const apiIdRaw = ctx.fields['api_id']
    const apiHash = ctx.fields['api_hash']
    if (!session) {
      throw new Error('No session_string on the credential. Run the interactive Setup wizard first.')
    }
    if (!apiIdRaw || !apiHash) throw new Error('Missing api_id / api_hash on the credential.')
    const apiId = Number(apiIdRaw)
    if (!Number.isFinite(apiId)) throw new Error('api_id must be numeric.')

    // Pre-connect wait — mirror bot adapter behaviour for the same reasons:
    //
    //   (a) Reactivate within same process (Stop+Start / settings save) → wait
    //       remainder of the 30s window since last deactivate. mtcute can hit
    //       AUTH_KEY_DUPLICATED if the previous client closed too recently and
    //       Telegram still considers the session live.
    //
    //   (b) Fresh boot (no entry in map) → wait `TELEGRAM_BOOT_POLL_DELAY_MS`
    //       (default 10s) so a previous container in a zero-downtime deploy has
    //       time to release its mtcute session before this one connects on the
    //       same `session_string`. Without this, both processes connect with
    //       the same auth_key and Telegram revokes one with AUTH_KEY_DUPLICATED.
    {
      const lastDeact = lastDeactivateByConnector.get(ctx.connectorId)
      if (lastDeact) {
        const elapsed = Date.now() - lastDeact
        const remain = REACTIVATE_WAIT_MS - elapsed
        if (remain > 0) {
          console.log(`[telegram.user] waiting ${Math.ceil(remain / 1000)}s for Telegram session-slot release before connecting`)
          await new Promise<void>(r => setTimeout(r, remain))
        }
      } else {
        const bootDelayMs = Number(process.env['TELEGRAM_BOOT_POLL_DELAY_MS'] ?? 10_000)
        if (bootDelayMs > 0) {
          console.log(`[telegram.user] fresh-boot wait ${Math.ceil(bootDelayMs / 1000)}s before connecting (lets old zero-downtime container release session)`)
          await new Promise<void>(r => setTimeout(r, bootDelayMs))
        }
      }
    }

    // mtcute v0.27 API: TelegramClient constructor only accepts core options
    // (apiId, apiHash, storage). Session is loaded via `client.start({ session })`
    // which ALSO starts the updates loop — without `start()`, no inbound updates
    // are dispatched to onNewMessage Emitter. Previously we used `connect()`
    // which only opens the network but doesn't enable updates dispatching.
    // Cast through unknown — actual mtcute TelegramClient has hundreds of
    // methods we don't bother typing. Runtime usage is duck-typed via the
    // narrow `MtcuteClient` interface + extra cast at use site.
    // const mod = await import('@mtcute/bun') as unknown as {
    //   TelegramClient: new (opts: { apiId: number; apiHash: string; storage?: string }) => MtcuteClient
    // }
    // const { TelegramClient } = mod
    // Per-credential SQLite storage path so multi-tenant userbots don't share
    // a single client.session file (would race + corrupt). Use connectorId.
    const storagePath = `userbot-${ctx.connectorId}.session`
    this.client = new TelegramClient({ apiId, apiHash, storage: storagePath })
    this.projectId = ctx.projectId
    this.connectorId = ctx.connectorId

    // Multi-tenant: each credential gets its OWN UserbotQueue (Plan §8b
    // quotas are per-Telegram-session, not shared). Build it now so we can
    // hand to the instance entry below.
    const instanceQueue = new UserbotQueue()
    const policyRaw = ctx.fields['queue_policy']
    if (policyRaw) {
      try {
        const parsed = JSON.parse(policyRaw) as Partial<UserbotQueuePolicy>
        instanceQueue.setPolicy(parsed)
      } catch { /* ignore — keep defaults */ }
    }
    instanceQueue.onEvent((event) => {
      console.log(`[telegram.user] queue event (connector=${ctx.connectorId}):`, event)
    })
    // Keep legacy scalar in sync so any code path that reads `this.queue`
    // gets the most-recent instance's queue (single-tenant fallback).
    this.queue = instanceQueue

    // Stash this credential's runtime state under its connectorId.
    this.userInstances.set(ctx.connectorId, {
      client: this.client,
      projectId: ctx.projectId,
      connectorId: ctx.connectorId,
      myUserId: null,
      myUsername: null,
      myIsPremium: false,
      queue: instanceQueue,
      activatedAt: Date.now(),
    })

    try {
      const c0 = this.client as TelegramClient
      // start() handles session import + auth check + updates loop in one go.
      // Falls back to connect()+importSession() for older mtcute builds.
      if (typeof c0.start === 'function') {
        await c0.start({ session })
        c0.onNewMessage.add((msg) => {
          console.log(msg.text)
        })
      } else if (typeof c0.importSession === 'function') {
        await c0.importSession(session)
        await this.client.connect()
      } else {
        await this.client.connect()
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      if (msg.includes('AUTH_KEY_UNREGISTERED') || msg.includes('AUTH_KEY_DUPLICATED')) {
        this.queue.markSessionExpired()
        // Surface a clear "session expired" so the credential UI prompts re-setup.
        throw new Error(`SESSION_EXPIRED: ${msg} — re-run the Setup wizard.`)
      }
      throw err
    }

    try {
      const me = await this.client.getMe()
      this.myUserId = String(me.id)
      this.myUsername = me.username ?? null
      this.myIsPremium = me.isPremium === true
      // Mirror identity into per-instance map.
      const inst = this.userInstances.get(ctx.connectorId)
      if (inst) {
        inst.myUserId = this.myUserId
        inst.myUsername = this.myUsername
        inst.myIsPremium = this.myIsPremium
      }
      this.con(ctx.connectorId)?.info(`Identity cached: @${this.myUsername ?? '(no username)'}`, { user_id: this.myUserId, premium: this.myIsPremium })
    } catch { /* non-fatal */ }

    // Inbound — wire 'new_message' to ConnectorEvent shape. mtcute's pub-sub
    // API name differs across versions / build flavours:
    //   - v0.x worker:        client.on('new_message', handler)
    //   - v0.27+ method:      client.onNewMessage.add(handler) / client.onNewMessage(handler)
    //   - dispatcher pattern: client.dispatcher.onNewMessage(handler)
    //   - updates namespace:  client.updates.on('new_message', handler)
    // Try each in order; first one that's a function wins. Failing all:
    // log + continue (outbound still works, just no inbound routing).
    const handler = (raw: unknown) => {
      try {
        // Diagnostic: every raw mtcute message arrival, BEFORE normalize.
        // Lets operator confirm whether the wired pub-sub method is firing
        // at all (separate from "normalize returned null"). Sample chat info
        // so we don't dump massive object — just enough to identify it.
        const r = raw as { id?: number | bigint; chat?: { id?: number | bigint; chatType?: string; title?: string }; sender?: { id?: number | bigint; username?: string }; text?: string }
        console.log(`[telegram.user] inbound raw: msg_id=${String(r?.id ?? 'n/a')} chat_id=${String(r?.chat?.id ?? 'n/a')} chat_type=${r?.chat?.chatType ?? 'n/a'} sender=@${r?.sender?.username ?? r?.sender?.id ?? 'n/a'} text_preview=${(r?.text ?? '').slice(0, 60)}`)
        // Pass ctx.connectorId so multi-tenant userbots produce events with the
        // RIGHT connector_id (legacy `this.connectorId` would point to the
        // most-recently-activated credential — wrong for credential A's inbound).
        const event = this.normalizeInbound(raw, ctx.connectorId)
        if (!event) {
          console.log(`[telegram.user] inbound DROPPED by normalize (msg_id=${String(r?.id ?? 'n/a')}) — likely missing required field`)
          return
        }
        // Mirror bot adapter's pattern: arrival row first (status=received),
        // OUTSIDE the routing pipeline, so connector_events table reflects
        // truth even if the router stalls. Without this, no row at all
        // appears in the Channels Events tab from inbound.
        if (this.connectorId) {
          logConnectorEvent({
            connector_id: this.connectorId!,
            event_type: event.type,
            direction: 'inbound',
            ref_keys: event.ref_keys,
            payload: event as unknown as Record<string, unknown>,
            raw_payload: raw,
            status: 'received',
          }).catch(() => {})
        }
        ctx.onEvent(event).catch(err => console.warn('[telegram.user] onEvent error:', err))
      } catch (err) {
        console.warn('[telegram.user] inbound normalize error:', err)
      }
    }
    // mtcute v0.27 API: emitters under `client.onNewMessage` / `client.onUpdate`
    // / `client.onRawUpdate`. Each is an `Emitter<T>` from @fuman/utils with
    // an `add(handler)` method. Old `client.on('new_message', ...)` does NOT
    // exist on this build — confirmed by inspecting node_modules/@mtcute.
    type EmitterLike = { add: (h: (v: unknown) => void) => void }
    const c = this.client as unknown as {
      onNewMessage?: EmitterLike
      onRawUpdate?: EmitterLike
      onUpdate?: EmitterLike
    }
    let wired = false
    const nm = c.onNewMessage
    if (nm && typeof nm.add === 'function') {
      try { nm.add(handler); wired = true } catch { /* try next */ }
    }
    // Fallback to onUpdate (parsed updates — needs filtering for 'new_message').
    const ou = c.onUpdate
    if (!wired && ou && typeof ou.add === 'function') {
      try {
        ou.add((u: unknown) => {
          const upd = u as { name?: string; data?: unknown }
          if (upd?.name === 'new_message' && upd.data) handler(upd.data)
        })
        wired = true
      } catch { /* try next */ }
    }
    if (!wired) {
      console.warn(`[telegram.user] could not wire inbound handler — no recognised mtcute pub-sub method found. Outbound + actions still work; inbound message routing is DISABLED until adapter is updated for this @mtcute/bun build.`)
    } else {
      console.log(`[telegram.user] inbound handler wired for connector=${ctx.connectorId}`)
    }

    console.log(`[telegram.user] activated — logged in as user_id=${this.myUserId}`)
    this.con(ctx.connectorId)?.info(`Userbot activated — user_id=${this.myUserId}`, { wired_inbound: wired })
  }

  override async onDeactivate(connectorId?: string): Promise<void> {
    // Multi-tenant: tear down ONLY the matching credential's instance. If
    // connectorId omitted (legacy callers), fall back to "the only one" or
    // refuse if multiple are active.
    let targetId: string | null = connectorId ?? null
    if (!targetId) {
      if (this.userInstances.size === 1) targetId = [...this.userInstances.keys()][0]!
      else if (this.userInstances.size > 1) {
        console.warn(`[telegram.user] onDeactivate() called WITHOUT connectorId while ${this.userInstances.size} credentials active — refusing (would tear down wrong one).`)
        return
      } else {
        return
      }
    }
    const inst = this.userInstances.get(targetId)
    if (!inst) return

    this.con(targetId)?.info('Userbot deactivating')
    lastDeactivateByConnector.set(targetId, Date.now())
    try { await inst.client.disconnect() } catch { /* best-effort */ }
    try { if (inst.client.close) await inst.client.close() } catch { /* best-effort */ }
    this.userInstances.delete(targetId)

    // If we just tore down the credential whose state lived in the legacy
    // scalars, repoint scalars to the next-newest remaining instance (or
    // null if none remain).
    if (this.connectorId === targetId) {
      this.client = null
      this.projectId = null
      this.connectorId = null
      this.myUserId = null
      this.myUsername = null
      this.myIsPremium = false
      const remaining = [...this.userInstances.values()].sort((a, b) => b.activatedAt - a.activatedAt)[0]
      if (remaining) {
        this.client = remaining.client as TelegramClient
        this.projectId = remaining.projectId
        this.connectorId = remaining.connectorId
        this.myUserId = remaining.myUserId
        this.myUsername = remaining.myUsername
        this.myIsPremium = remaining.myIsPremium
        this.queue = remaining.queue
      }
    }
    console.log(`[telegram.user] disconnected for connector=${targetId} (${this.userInstances.size} remain)`)
  }

  private myUsername: string | null = null
  private myIsPremium: boolean = false

  override getIdentity(connectorId?: string) {
    // Multi-tenant: return THIS connector's identity, not the legacy scalar.
    const inst = connectorId ? this.userInstances.get(connectorId) : null
    const username = inst?.myUsername ?? this.myUsername
    const userId = inst?.myUserId ?? this.myUserId
    const isPremium = inst?.myIsPremium ?? this.myIsPremium
    if (!userId && !username) return null
    return {
      name: username ?? `user:${userId}`,
      username: username ? `@${username}` : null,
      user_id: userId,
      metadata: {
        kind: 'userbot',
        is_premium: isPremium,
        connector_id: inst?.connectorId ?? this.connectorId ?? null,
      },
    }
  }

  override parseEvent(): ConnectorEvent | null {
    // Inbound events come through `client.on('new_message')` in onActivate
    // (push model, not pull). External webhook adapters use parseEvent; userbot
    // doesn't have one.
    return null
  }

  /**
   * Map an mtcute incoming message into the canonical ConnectorEvent shape.
   * This is best-effort — mtcute's wrapped Message has many fields; we pull
   * the ones the Jiku event-router cares about.
   */
  private normalizeInbound(raw: unknown, connectorIdHint?: string): ConnectorEvent | null {
    const m = raw as Record<string, unknown> & {
      id?: number
      chat?: { id?: number | bigint; chatType?: string; title?: string; username?: string; firstName?: string }
      sender?: { id?: number | bigint; isBot?: boolean; username?: string; firstName?: string }
      text?: string
      date?: Date | number
    }
    if (!m || typeof m !== 'object' || !m.id || !m.chat) return null
    const chatId = String(m.chat.id ?? '')
    if (!chatId) return null
    // Skip our own outbound — userbot also receives its own sent messages.
    // Resolve identity per-instance: if we know which connector this event
    // came in on (from the activate-time closure), use that instance's
    // myUserId — falls back to scalar for legacy callers.
    const inst = connectorIdHint ? this.userInstances.get(connectorIdHint) : null
    const myUserId = inst?.myUserId ?? this.myUserId
    if (m.sender && myUserId && String(m.sender.id ?? '') === myUserId) return null

    // mtcute discriminator: `Message.chat` returns `Peer = User | Chat`. Only
    // Chat instances have `.chatType` getter ('group' | 'supergroup' | 'channel'
    // | 'gigagroup' | 'monoforum'). Absence of `chatType` means the chat is a
    // User → DM. This was the bug behind "no pairing request appears" — old
    // code checked `chatType === 'group'` and got undefined for DMs (correct
    // behavior — DMs ARE chatType-less), but DM path's pending-identity flow
    // also runs only when scope_key is undefined (which it is for DMs anyway).
    // The actual fix here is making `chat_type` metadata accurate for both
    // branches so downstream / UI sees 'private' for DMs instead of 'n/a'.
    const ct = m.chat.chatType
    const isGroup = ct === 'group' || ct === 'supergroup' || ct === 'channel' || ct === 'gigagroup'
    const scopeKey = isGroup ? `group:${chatId}` : undefined
    const chatType: string = ct ?? 'private'  // No chatType ⇒ Peer is User ⇒ DM

    return {
      type: 'message',
      // IMPORTANT: this is the ADAPTER id ('jiku.telegram.user'), NOT the
      // connector UUID. event-router uses it to find which connector row
      // owns this event via `connector.plugin_id === event.connector_id`.
      // Putting a UUID here makes EVERY event silently drop because no
      // plugin_id will match (bot adapter pattern is the same — `this.id`).
      connector_id: this.id,
      ref_keys: { message_id: String(m.id), chat_id: chatId },
      scope_key: scopeKey,
      sender: {
        external_id: String(m.sender?.id ?? ''),
        display_name: m.sender?.firstName ?? m.sender?.username ?? undefined,
        username: m.sender?.username ?? undefined,
        is_bot: m.sender?.isBot === true,
      },
      content: { text: m.text ?? '', raw: m },
      metadata: {
        chat_title: m.chat.title ?? m.chat.firstName,
        chat_type: chatType,
        // Plan 25 add-on — reply context. mtcute exposes RepliedMessageInfo
        // via `m.replyToMessage` (getter). Snapshot the useful fields so the
        // event-router can inject a Reply chain into connector_context. The
        // raw object's getters don't survive JSON serialization, so we copy
        // explicit primitives here.
        ...(extractMtcuteReply(m as unknown as { replyToMessage?: unknown })),
      },
      raw_payload: m,
      timestamp: m.date instanceof Date ? m.date : new Date((Number(m.date ?? 0)) * 1000),
    }
  }

  override async sendMessage(target: ConnectorTarget, content: ConnectorContent): Promise<ConnectorSendResult> {
    // Multi-tenant: pick THIS target's client + queue (per-credential isolation).
    const client = this.clientFor(target.connector_id)
    const queue = this.queueFor(target.connector_id)
    if (!client) return { success: false, error: target.connector_id
      ? `No active userbot instance for connector_id=${target.connector_id}`
      : 'Userbot client not connected' }
    const chatId = target.ref_keys['chat_id']
    if (!chatId) return { success: false, error: 'Missing chat_id' }
    const text = content.text ?? ''
    if (!text) return { success: false, error: 'Empty text' }

    // mtcute v0.27 high-level API does NOT have parseMode in send opts —
    // `text: InputText` is `string | TextWithEntities`. Plain string = sent
    // raw (no parsing). Markdown rendering requires `TextWithEntities` from
    // mtcute's `md`-template helper (separate package). For now: send PLAIN.
    // Running `telegramifyMarkdown(...escape)` here was producing visible
    // backslashes (`\-`, `\\`) at the user's screen because Telegram never
    // parsed them — the parseMode flag was silently ignored.
    //
    // Future: import @mtcute/markdown-parser to support markdown formatting.
    const finalText = text
    const opts: Record<string, unknown> = {}
    if (content.params) {
      for (const [k, v] of Object.entries(content.params)) {
        if (v === undefined || v === null) continue
        opts[k] = v
      }
    }
    const peer = chatId.startsWith('-') || /^\d+$/.test(chatId) ? Number(chatId) : chatId

    // simulate_typing for userbot: real-account typing indicator + dwell time
    // proportional to text length (mimics human typing speed). Bot adapter
    // does fake-typing via edits; userbot can use the genuine TG typing
    // status which feels much more natural to the recipient.
    if (content.simulate_typing) {
      try {
        const c = client as MtcuteClient & { sendTyping?: (peer: string | number | bigint, status?: string) => Promise<unknown> }
        if (c.sendTyping) {
          await c.sendTyping(peer, 'typing').catch(() => {})
          // Dwell ≈ 30 chars/sec, capped 300ms-3000ms. Quick reply feels snappy,
          // long replies show meaningful "typing..." duration.
          const dwellMs = Math.min(3000, Math.max(300, Math.floor(finalText.length * 33)))
          await new Promise<void>(r => setTimeout(r, dwellMs))
        }
      } catch { /* best-effort */ }
    }

    try {
      this.con(target.connector_id)?.info(`outbound → chat_id=${chatId} len=${finalText.length}`, { chat_id: chatId })
      const queued = await queue.enqueue<{ id?: number; chat?: { id?: number | bigint } } | undefined>(
        { chatId },
        () => client.sendText(peer, finalText, opts) as Promise<{ id?: number; chat?: { id?: number | bigint } } | undefined>,
        'send_message',
      )
      const res = queued.result
      this.con(target.connector_id)?.info(`outbound OK message_id=${res?.id ?? 'n/a'}`, { chat_id: chatId })
      return {
        success: true,
        ref_keys: {
          message_id: String(res?.id ?? ''),
          chat_id: String(res?.chat?.id ?? chatId),
        },
        raw_payload: { ...res, queue: { delay_ms_applied: queued.delay_ms_applied } },
      }
    } catch (err) {
      return mapQueueError(err)
    }
  }

  /**
   * Userbot-exclusive action: forward with `drop_author` (hide sender + preserve
   * Premium animated custom_emoji). Phase 4 will register this as a proper
   * `connector_run_action` entry; for now it's a method other code can call.
   */
  async forwardDropAuthor(opts: { from_chat_id: string | number; message_ids: number[]; to_chat_id: string | number }): Promise<ConnectorSendResult> {
    if (!this.client) return { success: false, error: 'Userbot client not connected' }
    try {
      const res = await this.client.forwardMessagesById({
        fromChatId: opts.from_chat_id,
        messages: opts.message_ids,
        toChatId: opts.to_chat_id,
        noAuthor: true,
      })
      return { success: true, raw_payload: res }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      return { success: false, error: msg }
    }
  }

  /**
   * Userbot-exclusive: read full chat history past Bot API's 100-message cap.
   */
  async getChatHistory(peer: string | number, limit = 50, offsetId = 0): Promise<Array<Record<string, unknown>>> {
    if (!this.client) throw new Error('Userbot client not connected')
    return this.client.getHistory(peer, { limit, offsetId })
  }

  // ─── Plan 24 Phase 4 — Action registry ────────────────────────────────────

  override readonly actions: ConnectorAction[] = [
    {
      id: 'forward_message',
      name: 'Forward Message',
      description: 'Forward one or more messages from a source chat to a destination chat. With hide_sender:true (USERBOT-ONLY: works correctly), the "Forwarded from" header is suppressed AND animated Premium custom_emoji are preserved — Bot API copyMessage cannot do this.',
      params: {
        from_chat_id: { type: 'string', description: 'Source chat_id (where the messages came from)', required: true },
        to_chat_id: { type: 'string', description: 'Destination chat_id', required: true },
        message_ids: { type: 'string', description: 'Comma-separated message IDs to forward, e.g. "123,124,125"', required: true },
        hide_sender: { type: 'boolean', description: 'Hide the "Forwarded from" header AND preserve Premium custom_emoji animation. Default true on userbot.', required: false },
      },
    },
    {
      id: 'get_chat_history',
      name: 'Get Chat History',
      description: 'Read past N messages from a chat. Supports arbitrary offset (Bot API limited to ~100). USERBOT-ONLY.',
      params: {
        peer: { type: 'string', description: 'Chat ID, username, or invite link', required: true },
        limit: { type: 'number', description: 'Number of messages to fetch (default 50, max 200)', required: false },
        offset_id: { type: 'number', description: 'Start offset — fetch messages BEFORE this message_id (for pagination)', required: false },
      },
    },
    {
      id: 'get_dialogs',
      name: 'Get Dialogs',
      description: 'List all chats this account is currently in. USERBOT-ONLY.',
      params: {
        limit: { type: 'number', description: 'Max number of dialogs to return (default 30)', required: false },
      },
    },
    {
      id: 'set_typing',
      name: 'Set Typing',
      description: 'Show "typing…" indicator in a chat. USERBOT-ONLY (longer-running than Bot API).',
      params: {
        chat_id: { type: 'string', description: 'Chat to show typing in', required: true },
      },
    },
    {
      id: 'edit_message',
      name: 'Edit Message',
      description: 'Edit the text of a previously sent message.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        message_id: { type: 'string', description: 'Message ID', required: true },
        text: { type: 'string', description: 'New text', required: true },
        markdown: { type: 'boolean', description: 'Parse text as MarkdownV2', required: false },
      },
    },
    // ─── Parity with TelegramBotAdapter ────────────────────────────────────
    {
      id: 'send_photo',
      name: 'Send Photo',
      description: 'Send a photo by URL or file path. Supports caption with markdown.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        url: { type: 'string', description: 'Public URL of the photo (https://...)', required: false },
        path: { type: 'string', description: 'Local path on the project virtual disk (e.g. "/assets/banner.jpg")', required: false },
        caption: { type: 'string', description: 'Caption text (Telegram cap: 1024 chars)', required: false },
        markdown: { type: 'boolean', description: 'Parse caption as MarkdownV2', required: false },
      },
    },
    {
      id: 'send_document',
      name: 'Send Document',
      description: 'Send a file by URL or file path. Any non-photo content (PDFs, archives, generic files).',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        url: { type: 'string', description: 'Public URL of the document', required: false },
        path: { type: 'string', description: 'Local path on the project disk', required: false },
        filename: { type: 'string', description: 'Override file name shown in Telegram', required: false },
        caption: { type: 'string', description: 'Caption text', required: false },
        markdown: { type: 'boolean', description: 'Parse caption as MarkdownV2', required: false },
      },
    },
    {
      id: 'copy_message',
      name: 'Copy Message',
      description: 'Copy a message to another chat WITHOUT a "Forwarded from" header. Bot API behaves the same; userbot here delegates to forward_message with hide_sender:true for parity.',
      params: {
        from_chat_id: { type: 'string', description: 'Source chat_id', required: true },
        to_chat_id: { type: 'string', description: 'Destination chat_id', required: true },
        message_id: { type: 'string', description: 'Single message_id to copy', required: true },
      },
    },
    {
      id: 'get_chat_info',
      name: 'Get Chat Info',
      description: 'Fetch chat metadata (title, type, member count, description, invite_link if any).',
      params: {
        chat_id: { type: 'string', description: 'Chat ID, username, or invite link', required: true },
      },
    },
    // ─── Userbot-EXCLUSIVE (Bot API does NOT support these) ───────────────
    {
      id: 'mark_read',
      name: 'Mark Read',
      description: 'Mark messages in a chat as read up to a given message_id. USERBOT-ONLY — bots cannot mark-read on behalf of users. Useful when the agent has consumed inbound silently and wants to clear unread state for the human owner.',
      params: {
        chat_id: { type: 'string', description: 'Chat ID', required: true },
        max_id: { type: 'number', description: 'Mark all messages up to and including this id as read', required: false },
      },
    },
    {
      id: 'search_messages',
      name: 'Search Messages',
      description: 'Search messages globally or within a chat by text. USERBOT-ONLY.',
      params: {
        query: { type: 'string', description: 'Search text', required: true },
        chat_id: { type: 'string', description: 'Limit search to one chat (omit for global search)', required: false },
        limit: { type: 'number', description: 'Max results (default 30)', required: false },
      },
    },
    {
      id: 'get_user_info',
      name: 'Get User Info',
      description: 'Detailed user profile (full name, bio, photos, common chats). USERBOT-ONLY.',
      params: {
        user: { type: 'string', description: 'User id, @username, or +phone', required: true },
      },
    },
  ]

  /** Snapshot of the userbot queue — surfaced via `connector_get_queue_status`. */
  getQueueStatus(connectorId?: string) {
    const queue = this.queueFor(connectorId)
    return queue.status()
  }

  override async runAction(actionId: string, params: Record<string, unknown>, connectorId?: string): Promise<unknown> {
    // Multi-tenant: resolve client + queue for the right credential.
    const client = this.clientFor(connectorId)
    const queue = this.queueFor(connectorId)
    if (!client) throw new Error('Userbot client not connected for this connector')
    const c = client as MtcuteClient & {
      getDialogs?: (opts?: { limit?: number }) => Promise<Array<Record<string, unknown>>>
      sendTyping?: (peer: string | number | bigint, status?: string) => Promise<unknown>
      editMessage?: (opts: { chatId: string | number | bigint; message: number; text: string; parseMode?: string }) => Promise<unknown>
    }

    const peerOf = (raw: unknown): string | number => {
      const s = String(raw ?? '')
      if (!s) throw new Error('Missing peer / chat_id')
      return /^-?\d+$/.test(s) ? Number(s) : s
    }

    const idsOf = (raw: unknown): number[] => String(raw ?? '').split(',').map(s => Number(s.trim())).filter(n => Number.isFinite(n))

    // Every action goes through the queue. Scope is chat-level when
    // the action targets a specific chat, '_global' for session-wide ones.
    const enqueue = <T>(scope: { chatId: string | '_global' }, fn: () => Promise<T>) =>
      queue.enqueue(scope, fn, actionId)

    try {
      if (actionId === 'forward_message') {
        const hideSender = params['hide_sender'] !== false
        const queued = await enqueue({ chatId: String(params['from_chat_id']) }, () => c.forwardMessagesById({
          fromChatId: peerOf(params['from_chat_id']),
          messages: idsOf(params['message_ids']),
          toChatId: peerOf(params['to_chat_id']),
          noAuthor: hideSender,
        }))
        return { success: true, hide_sender: hideSender, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'get_chat_history') {
        const limit = Math.min(Number(params['limit'] ?? 50), 200)
        const offsetId = Number(params['offset_id'] ?? 0)
        const queued = await enqueue({ chatId: String(params['peer']) }, () => c.getHistory(peerOf(params['peer']), { limit, offsetId }))
        return { success: true, count: queued.result.length, messages: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'get_dialogs') {
        if (!c.getDialogs) return { success: false, error: 'mtcute client does not expose getDialogs in this build' }
        const limit = Math.min(Number(params['limit'] ?? 30), 200)
        const queued = await enqueue({ chatId: '_global' }, () => c.getDialogs!({ limit }))
        return { success: true, count: queued.result.length, dialogs: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'set_typing') {
        if (!c.sendTyping) return { success: false, error: 'mtcute client does not expose sendTyping in this build' }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => c.sendTyping!(peerOf(params['chat_id']), 'typing'))
        return { success: true, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'edit_message') {
        if (!c.editMessage) return { success: false, error: 'mtcute client does not expose editMessage in this build' }
        const text = String(params['text'] ?? '')
        const useMd = params['markdown'] === true
        const finalText = useMd ? telegramifyMarkdown(text, 'escape') : text
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => c.editMessage!({
          chatId: peerOf(params['chat_id']),
          message: Number(params['message_id']),
          text: finalText,
          parseMode: useMd ? 'MarkdownV2' : undefined,
        }))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      // ─── Parity actions ──────────────────────────────────────────────────
      const cExt = c as MtcuteClient & {
        sendMedia?: (chatId: string | number | bigint, media: unknown, opts?: Record<string, unknown>) => Promise<unknown>
        sendPhoto?: (chatId: string | number | bigint, photo: unknown, opts?: Record<string, unknown>) => Promise<unknown>
        sendDocument?: (chatId: string | number | bigint, document: unknown, opts?: Record<string, unknown>) => Promise<unknown>
        readHistory?: (chatId: string | number | bigint, opts?: { maxId?: number }) => Promise<unknown>
        searchGlobal?: (query: string, opts?: { limit?: number }) => Promise<Array<Record<string, unknown>>>
        searchMessages?: (opts: { chatId?: string | number | bigint; query: string; limit?: number }) => Promise<Array<Record<string, unknown>>>
        getFullUser?: (userId: string | number | bigint) => Promise<Record<string, unknown>>
        getChat?: (chatId: string | number | bigint) => Promise<Record<string, unknown>>
        resolvePeer?: (peer: string | number | bigint) => Promise<Record<string, unknown>>
      }

      if (actionId === 'send_photo') {
        const url = params['url'] as string | undefined
        const path = params['path'] as string | undefined
        if (!url && !path) return { success: false, error: 'send_photo requires either `url` or `path`' }
        const send = cExt.sendPhoto ?? cExt.sendMedia
        if (!send) return { success: false, error: 'mtcute build does not expose sendPhoto / sendMedia' }
        const caption = params['caption'] as string | undefined
        const useMd = params['markdown'] === true
        const opts: Record<string, unknown> = {}
        if (caption) opts['caption'] = useMd ? telegramifyMarkdown(caption, 'escape') : caption
        if (caption && useMd) opts['parseMode'] = 'MarkdownV2'
        // For URL: pass directly. For path: read file from project virtual disk.
        let media: unknown = url
        if (!url && path) {
          if (!this.projectId) return { success: false, error: 'No active project for path resolution' }
          const fs = await getFilesystemService(this.projectId)
          if (!fs) return { success: false, error: 'Filesystem not configured for this project' }
          const file = await fs.read(path)
          media = file.content.startsWith('__b64__:')
            ? Buffer.from(file.content.replace('__b64__:', ''), 'base64')
            : Buffer.from(file.content, 'utf-8')
        }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => send.call(cExt, peerOf(params['chat_id']), media, opts))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'send_document') {
        const url = params['url'] as string | undefined
        const path = params['path'] as string | undefined
        if (!url && !path) return { success: false, error: 'send_document requires either `url` or `path`' }
        const send = cExt.sendDocument ?? cExt.sendMedia
        if (!send) return { success: false, error: 'mtcute build does not expose sendDocument / sendMedia' }
        const caption = params['caption'] as string | undefined
        const useMd = params['markdown'] === true
        const opts: Record<string, unknown> = {}
        if (caption) opts['caption'] = useMd ? telegramifyMarkdown(caption, 'escape') : caption
        if (caption && useMd) opts['parseMode'] = 'MarkdownV2'
        if (params['filename']) opts['fileName'] = String(params['filename'])
        let media: unknown = url
        if (!url && path) {
          if (!this.projectId) return { success: false, error: 'No active project for path resolution' }
          const fs = await getFilesystemService(this.projectId)
          if (!fs) return { success: false, error: 'Filesystem not configured for this project' }
          const file = await fs.read(path)
          media = file.content.startsWith('__b64__:')
            ? Buffer.from(file.content.replace('__b64__:', ''), 'base64')
            : Buffer.from(file.content, 'utf-8')
        }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => send.call(cExt, peerOf(params['chat_id']), media, opts))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'copy_message') {
        // Userbot has no native "copy" — forward with hide_sender:true gives the
        // same UX (no header) but with custom_emoji preservation as bonus.
        const queued = await enqueue({ chatId: String(params['from_chat_id']) }, () => c.forwardMessagesById({
          fromChatId: peerOf(params['from_chat_id']),
          messages: [Number(params['message_id'])],
          toChatId: peerOf(params['to_chat_id']),
          noAuthor: true,
        }))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'get_chat_info') {
        const get = cExt.getChat ?? cExt.resolvePeer
        if (!get) return { success: false, error: 'mtcute build does not expose getChat / resolvePeer' }
        const queued = await enqueue({ chatId: '_global' }, () => get.call(cExt, peerOf(params['chat_id'])))
        return { success: true, chat: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      // ─── Userbot-EXCLUSIVE ───────────────────────────────────────────────
      if (actionId === 'mark_read') {
        if (!cExt.readHistory) return { success: false, error: 'mtcute build does not expose readHistory' }
        const queued = await enqueue({ chatId: String(params['chat_id']) }, () => cExt.readHistory!(peerOf(params['chat_id']), {
          maxId: params['max_id'] !== undefined ? Number(params['max_id']) : undefined,
        }))
        return { success: true, result: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      if (actionId === 'search_messages') {
        const query = String(params['query'] ?? '')
        if (!query) return { success: false, error: 'query required' }
        const limit = Math.min(Number(params['limit'] ?? 30), 100)
        const chatId = params['chat_id'] as string | undefined
        if (chatId && cExt.searchMessages) {
          const queued = await enqueue({ chatId: String(chatId) }, () => cExt.searchMessages!({
            chatId: peerOf(chatId), query, limit,
          }))
          return { success: true, count: queued.result.length, messages: queued.result, delay_ms_applied: queued.delay_ms_applied }
        }
        if (!chatId && cExt.searchGlobal) {
          const queued = await enqueue({ chatId: '_global' }, () => cExt.searchGlobal!(query, { limit }))
          return { success: true, count: queued.result.length, messages: queued.result, delay_ms_applied: queued.delay_ms_applied }
        }
        return { success: false, error: 'mtcute build does not expose searchMessages / searchGlobal' }
      }

      if (actionId === 'get_user_info') {
        if (!cExt.getFullUser) return { success: false, error: 'mtcute build does not expose getFullUser' }
        const queued = await enqueue({ chatId: '_global' }, () => cExt.getFullUser!(peerOf(params['user'])))
        return { success: true, user: queued.result, delay_ms_applied: queued.delay_ms_applied }
      }

      return { success: false, error: `Unknown action: ${actionId}` }
    } catch (err) {
      return mapQueueError(err)
    }
  }

  override async sendTyping(target: ConnectorTarget): Promise<void> {
    const chatId = target.ref_keys['chat_id']
    if (!chatId || !this.client) return
    const c = this.client as MtcuteClient & { sendTyping?: (peer: string | number | bigint, status?: string) => Promise<unknown> }
    if (c.sendTyping) {
      await c.sendTyping(/^-?\d+$/.test(chatId) ? Number(chatId) : chatId, 'typing').catch(() => {})
    }
  }
}

export const telegramUserAdapter = new TelegramUserAdapter()
export { TelegramUserAdapter }

/**
 * Extract reply context from a mtcute Message into a plain JSON-safe object
 * suitable for `event.metadata.reply_to`. Uses duck typing because mtcute's
 * RepliedMessageInfo is a class with getters that don't survive JSON.
 */
function extractMtcuteReply(m: { replyToMessage?: unknown }): { reply_to?: Record<string, unknown> } {
  const r = m.replyToMessage as
    | {
        id?: number | null
        origin?: string
        chat?: { id?: number | bigint } | null
        sender?: { id?: number | bigint; username?: string; firstName?: string; displayName?: string } | null
        quoteText?: string
        isQuote?: boolean
        threadId?: number | null
      }
    | null
    | undefined
  if (!r || typeof r !== 'object') return {}
  const id = r.id ?? null
  if (id === null && !r.sender) return {}  // nothing useful
  const reply_to: Record<string, unknown> = {
    origin: r.origin ?? 'same_chat',
    is_quote: r.isQuote === true,
  }
  if (id !== null) reply_to['message_id'] = String(id)
  if (r.chat?.id != null) reply_to['chat_id'] = String(r.chat.id)
  if (r.threadId != null) reply_to['thread_id'] = String(r.threadId)
  if (r.sender) {
    reply_to['sender'] = {
      id: r.sender.id != null ? String(r.sender.id) : null,
      username: r.sender.username ?? null,
      display_name: r.sender.displayName ?? r.sender.firstName ?? null,
    }
  }
  if (r.quoteText) reply_to['quote_text'] = r.quoteText
  return { reply_to }
}
